### ISSUE TITLE
依赖更新后，包没有重新编译

### ISSUE THREAD

**Issue by xiaosong0911** [arch4edu/arch4edu#10]
感谢你们提供的方便的二进制源！可以节省不少编译时间。

我在使用你们的paraview包。paraview包依赖protobuf，protobuf包更新较为频繁，但paraview包的更新经常几个月不更新，这就导致更名后的动态连接库无法被正常使用：
```
$ paraview
/usr/lib/paraview-5.4/paraview: error while loading shared libraries: libprotobuf.so.14: cannot open shared object file: No such file or directory
```

我检查了一下你们的PKGBUILD，与AUR一致。应该只要重新编译就行。

为了永久的解决这个问题，建议你们做一个脚本，定时自动检查官方仓库更新，并对依赖有更新的包重新编译发布。

**Comment by petronny** [comment]
已经rebuild
现在还没有做这个脚本的计划
还是先靠人工吧。。。
