### ISSUE TITLE
paraview-opt outdated dependency

### ISSUE THREAD

**Issue by adrianinsaval** [arch4edu/arch4edu#100]
Current paraview-opt package depends on libjsoncpp=22-64 however current version in repositories is 24-64 so pacman doesn't want to upgrade. Please rebuild this package with the current version. I'm actually running manjaro but this should be a problem for arch too.

**Comment by petronny** [comment]
9904f09

**Comment by petronny** [comment]
Hi, there is an issue to discuss about the manjaro support at #169.
