### ISSUE TITLE
openboard needs rebuild

### ISSUE THREAD

**Issue by iyanmv** [arch4edu/arch4edu#103]
Hi,

`openboard` package needs to be rebuilt.

```
$ openboard
openboard: error while loading shared libraries: libpoppler.so.101: cannot open shared object file: No such file or directory
```
```
$ checkrebuild -i arch4edu
foreign google-earth-pro
arch4edu        intel-fortran-compiler
foreign mathematica
arch4edu        openboard
```

**Comment by petronny** [comment]
Thanks for the report!

BTW, where can I find the `checkrebuild` command?

**Comment by petronny** [comment]
0e61c699d7a41a93d9f3943a353053edcd100983

**Comment by iyanmv** [comment]
Hi, sorry for not answering before. I use this package:
https://aur.archlinux.org/packages/rebuild-detector/
https://github.com/maximbaz/rebuild-detector
