### ISSUE TITLE
[Request] petsc-complex

### ISSUE THREAD

**Issue by cauachagas** [arch4edu/arch4edu#104]
`PETSc` is a well known suite for solving PDE problems in Parallel. It is used as dependencies of `FEniCS`/`Dolfin`/`Firedrike` and `FreeFem`. There is a aur version https://aur.archlinux.org/packages/petsc. 

For the complex support 

`CONFOPTS=${CONFOPTS} --with-scalar-type=complex`

## Add optional superlu_dist support

```bash
# Add superlu_dist support
SUPERLU_DIST_DIR="/usr/include/superlu_dist"
if [ -d "${SUPERLU_DIST_DIR}" ]; then
	CONFOPTS="${CONFOPTS} --with-superlu_dist=1 --with-superlu_dist-lib=-lsuperlu_dist --with-superlu_dist-include=${SUPERLU_DIST_DIR}"
fi
```

## Problems with complex support

The `trilinos` support must be removed.

```bash
# Cannot use ml with complex numbers it is not coded for this capability
# if [ -f "/usr/lib/libml.so" ]; then
# 	CONFOPTS="${CONFOPTS} --with-ml=1"
# 	# Add boost support (may be useful for trilinos)
# 	CONFOPTS="${CONFOPTS} --with-boost=1"
# fi
```

**Comment by petronny** [comment]
Hi, there is already an petsc-complex package on AUR.

Could you contact the maintainer to update it and include your changes?

**Comment by cauachagas** [comment]
The purpose of the request is to make `arch4edu` provide the binaries, because the compilation takes a reasonable amount of time and memory. There are also `trilinos`, `mumps-par` e `superlu_dist` in the AUR, but `arch4edu` provides the binaries for all of them.

**Comment by petronny** [comment]
39d3a42efc4ea7402637d561df8f3eebbef46bf2
