### ISSUE TITLE
[Package request] chromium-vaapi

### ISSUE THREAD

**Issue by TheBlutarch** [arch4edu/arch4edu#107]
Can someone build chromium-vaapi please?
Nvidia users still depend on it and it recently vanished.
It takes ages for my system to build

**Comment by aviallon** [comment]
It takes ages for any system to build unfortunately :( 
Do you really need it ? I'm using an Nvidia GPU (RTX 2070S) with proprietary drivers, and I don't run into any issues with Chromium from Arch official repos, with all GPU flags enabled

```
Data exported | 2020-12-05T10:56:11.019Z
-- | --
Chrome version | Chrome/87.0.4280.88
Operating system | Linux 5.9.11-xanmod1-1
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/89e2380a3e36c3464b5dd1302349b1382549290d/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/89e2380a3e36c3464b5dd1302349b1382549290d/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | unknown hash
2D graphics backend | Skia/87 489348851cca51b23f522734b6db3c785ffdfaed
Command Line | /usr/lib/chromium/chromium --ppapi-flash-version=32.0.0.453 --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --flag-switches-begin --enable-accelerated-video-decode --enable-gpu-rasterization --enable-zero-copy --ignore-gpu-blocklist --enable-features=DecodeJpeg420ImagesToYUV,DecodeLossyWebPImagesToYUV,Vulkan --flag-switches-end
```
```
GPU0: VENDOR= 0x10de [Google Inc.], DEVICE=0x1e84 [ANGLE (NVIDIA Corporation, GeForce RTX 2070 SUPER/PCIe/SSE2, OpenGL 4.5 core)] *ACTIVE*
Driver vendor: Nvidia
Driver version: 455.45.01
```

**Comment by TheBlutarch** [comment]
So the official repo now includes the patch for va-api and the separate package is not needed anymore. Some online forums suggest that the official arch chromium package has va-api patches but not the vdpau patches needed for nvidia, but after testing it, that doesnt seem to be the case. Also, if for some reason, someone still needs the prebuilt package for chromium-vaapi, it is available on the opensuse build service, the link to which has been provided in the pinned comments on the official aur page for chromium-vaapi. I'll be closing this issue now, thank you for the support.
