### ISSUE TITLE
French mirror for arch4edu

### ISSUE THREAD

**Issue by aviallon** [arch4edu/arch4edu#109]
Hello, I host a mirror of arch4edu in France at https://mirror.lesviallon.fr/arch4edu/
It runs on my professional server (I'm a independent whose enterprise's name is Antoine Viallon)
Uptime can be verified at https://stats.lesviallon.fr

**Comment by aviallon** [comment]
Forgot to mention it was synced every six hours

**Comment by petronny** [comment]
https://github.com/arch4edu/mirrorlist/commit/cd5cbde8672f8e3355054bf679523b7ec5d88c66
Thanks for providing the mirror!
