### ISSUE TITLE
Package Request: oracle-xe

### ISSUE THREAD

**Issue by SunnyRaj84348** [arch4edu/arch4edu#112]
Oracle Database Express Edition (Oracle Database XE) is a free, smaller-footprint edition of Oracle Database. With oracle-xe, one can Administer the database. Create tables, views, and other database objects. Import, export, and view table data. Run queries and SQL scripts.

Homepage: https://www.oracle.com/in/database/technologies/appdev/xe.html

AUR: https://aur.archlinux.org/packages/oracle-xe

**Comment by petronny** [comment]
1f0e795
