### ISSUE TITLE
My mirror for arch4edu, located in Germany

### ISSUE THREAD

**Issue by kescherCode** [arch4edu/arch4edu#113]
Hello, I host a mirror for arch4edu, and would like to have it listed in your mirrorlist.

Server location: Germany
Organization: Jeremy Kescher
Mirror URL: https://arch4edu.mirror.kescher.at

Additionally, I offer a (currently limited to four slots at a time) rsync service for other mirrors at: `rsync://arch4edu.mirror.kescher.at/mirror/arch4edu/`, since no mirror (other than the source) currently does that, I thought that might be a sensible idea.
Uptime can be monitored here from now on: https://status.kescher.at/history/arch4edu-mirror

**Comment by kescherCode** [comment]
Sidenote: In order to encourage more mirrors for arch4edu, I have gone ahead and created this gist with mirror scripts, one being configured for the source mirror, and one being configured for mine: https://gist.github.com/kescherCode/7957f487e8cd04206619fbc94ac620ea

**Comment by petronny** [comment]
Many thanks!

Your site is included in the mirrorlist and your scripts are mentioned in the wiki page now.

**Comment by ngoonee** [comment]
This mirror seems to have stopped updating for a while? @kescherCode
