### ISSUE TITLE
Another new mirror in Germany

### ISSUE THREAD

**Issue by sandtler** [arch4edu/arch4edu#114]
Hi, I have recently set up an arch4edu mirror and would like to request being listed in your official mirrorlist.

- Country: Germany (DE)
- Institution: Felix Kopp
- URL (https): `https://mirror.autisten.club/arch4edu`
- URL (rsync): `rsync://mirror.autisten.club/arch4edu`

Additional note: Unfortunately, your origin server appears to be dropping traffic originating from my IP address (likely due to it being associated to a TOR relay). Therefore, I am not syncing from `rsync://mirrors.tuna.tsinghua.edu.cn/arch4edu` but rather `rsync://oblivia.kescher.at/mirror/arch4edu`.

**Comment by petronny** [comment]
Thank you for bringing us more mirror.

Your site in included in the mirrorlist.
