### ISSUE TITLE
openboard not launching

### ISSUE THREAD

**Issue by kouider01** [arch4edu/arch4edu#119]
the included openboard package just won't launch after installation.
all i get is this message 
"openboard: error while loading shared libraries: libpoppler.so.109: cannot open shared object file: No such file or directory"
the solution i found is to recompile package, which explains the fact that the aur/openboard package works properly after install.

**Comment by petronny** [comment]
`libpoppler.so.109` is provided by poppler 21.03.0-1 .

Could you confirm that you have this package installed?

**Comment by petronny** [comment]
Please reopen if it happens again.
