### ISSUE TITLE
Could package arch4edu-keyring itself added in arch4edu?

### ISSUE THREAD

**Issue by hzhangxyz** [arch4edu/arch4edu#120]
Just want `pacman -Qm` leave an empty output.

**Comment by petronny** [comment]
Alright.

But you still have to build it from AUR for the first time since it's not signed by TU.

**Comment by hzhangxyz** [comment]
What I want to do is  `pacman -Syu arch4edu-keyring` and it complain key, then `pacman -U` it from `/var/xxx` :)
