### ISSUE TITLE
python-pytorch-rocm installed but can't import torch

### ISSUE THREAD

**Issue by DomBito** [arch4edu/arch4edu#121]
This page has some information to check if the installation worked:
https://github.com/aieater/rocm_pytorch_informations

rocm-smi and clinfo worked as expected, but trying to import torch
`python3 -c 'import torch;print("GPU:",torch.cuda.is_available())'`
gave me
`GPU: False`

I this expected?

**Comment by petronny** [comment]
Please wait for #101
