### ISSUE TITLE
[Qestion/Answered] Build system

### ISSUE THREAD

**Issue by aviallon** [arch4edu/arch4edu#124]
Hello, I would like to know:
what kind of build system do you use to automate your package building without having too much issues? Is it able to detect when a package needs to be rebuilt automatically?
Thank you,
Antoine Viallon

**Comment by petronny** [comment]
We are using a variant of [lilac](https://github.com/archlinuxcn/lilac) which is the build bot for archlinuxcn as our build system.

It is able to automatically detect when a package needs to be rebuilt if the upstreams have been configurated properly.

In [this example](https://github.com/arch4edu/arch4edu/blob/master/python-numba/lilac.yaml),
There are 2 upstreams are used for this package.
Then it will be automatically when:
1. A update from AUR is detected.
2. A major update of python is detected.

Technically, the rebuild can also be trigger by a web page update and update the PKGBUILD on AUR.
This feature has already been implemented in lilac for a long time.
But we don't recommend such uses in arch4edu.
The packages in arch4edu should follow their upstreams in AUR. Not the opposite.

**Comment by aviallon** [comment]
This is an awesome program, thank you. It'll help for my `xanmod` repo :)

**Comment by petronny** [comment]
Please feel free to ask if you have more questions.
