### ISSUE TITLE
yay needs rebuild (very urgently)

### ISSUE THREAD

**Issue by kescherCode** [arch4edu/arch4edu#127]
arch4edu will currently break any installations of yay as soon as pacman is updated to 6.0.0. The maintainer has already bumped the pkgrel to cause rebuilds.

**Comment by aviallon** [comment]
Indeed, there is a new soname for libalpm

**Comment by aviallon** [comment]
@petronny

**Comment by petronny** [comment]
c04e0cc 5b95e80 9207b95 f9f1d7b
