### ISSUE TITLE
python-tensorflow-rocm need update and rebuild

### ISSUE THREAD

**Issue by maz-1** [arch4edu/arch4edu#132]
current package is linked against icu68 while archlinux has upgraded to icu69
Also archlinux has upgraded python-wrapt to 1.12 which is not compatible with current package.

**Comment by aviallon** [comment]
I confirm this. It no longer works, and is late by 2 minor versions.

**Comment by aviallon** [comment]
@petronny do you know why it is not being updated anymore?

**Comment by acxz** [comment]
@petronny I think this issue can be closed for now. Once I get python-tensorflow-rocm working in a clean chroot, I'll make an issue here again. Feel free to remove python-tensorflow-rocm form arch4edu as of now.

**Comment by petronny** [comment]
We still cannot build tensorflow-rocm successfully.
But tensorflow-amd could be built, which uses an upstream forked by rocm.
So it has been added into arch4edu and could be a replacement to tensorflow-rocm until it's ready.

**Comment by petronny** [comment]
0fb0783
