### ISSUE TITLE
Slight confusion with the "Add arch4edu to your Archlinux" wiki page

### ISSUE THREAD

**Issue by kescherCode** [arch4edu/arch4edu#136]
The [Add arch4edu to your Archlinux](https://github.com/arch4edu/arch4edu/wiki/Add-arch4edu-to-your-Archlinux) page has a bit of inconsistency - it incorrectly says to install `devtools-arch4edu`, while the links (correctly) point to installing `arch4edu-keyring`.

**Comment by petronny** [comment]
Oops, fixed.
