### ISSUE TITLE
qemu-user-static{,bin} need upgrades to newer version

### ISSUE THREAD

**Issue by kescherCode** [arch4edu/arch4edu#137]
AUR packages are at 6.1.0-1 and 6.1-1 respectively, while arch4edu is at 6.0.0-1 and 6.0-1.

**Comment by petronny** [comment]
de71ba89ac081892ef114e8d0fa1d9e245c80f08
b8e6c711307e1d3ac9c0e7ad0ea0dbc674d038ee
