### ISSUE TITLE
Package Request: alice-vision

### ISSUE THREAD

**Issue by KenwoodFox** [arch4edu/arch4edu#140]
Alice vision has a lot of tools for computer image reconstruction, ive been using it a lot in some of my recent classes, but it takes forever to build and admitidly, i cant keep my installs working for longer than a week or so, once a new release comes out it never builds cleanly and ususally throws a dependency error or something...

would be nice to have a binary version somewhere, even if it was held a bit behind to address weirdness during build?

Thanks so much for reading

**Comment by KenwoodFox** [comment]
https://aur.archlinux.org/packages/alice-vision/

**Comment by KenwoodFox** [comment]
Should I try and make a PR for it here? Is that how this works?

**Comment by petronny** [comment]
Yeah you can try to make a PR for this package.
I've just updated to guide in [wiki](https://github.com/arch4edu/arch4edu/wiki/Add-a-package-to-arch4edu).

**Comment by petronny** [comment]
With the help of a new script to automatically import packages and their dependencies, adding package with dependencies seems to be much easier.
`alice-vision` has been added to the repository now. You can visit https://arch4edu.github.io/ to check the build logs or help fixing the builds.

**Comment by KenwoodFox** [comment]
Awesome thank you so much, i took a look at the build, thats.. a lot, and im no ninja expert but ill work thru it~ hopefully i can put a PR together

**Comment by petronny** [comment]
https://github.com/arch4edu/arch4edu/commit/71497516ceea0133b1059b62b907915713344cad
