### ISSUE TITLE
New package structure with ROCm 4.5.0

### ISSUE THREAD

**Issue by tpkessler** [arch4edu/arch4edu#141]
With ROCm 4.5.0 there are several changes in the package structure, including:

# New names
- [x] `llvm-amdgpu` is now [`rocm-llvm`](https://aur.archlinux.org/packages/rocm-llvm/)
- [x] `hip-rocclr` is now [`hip-runtime-amd`](https://aur.archlinux.org/packages/hip-runtime-amd/)

# New packages
- [x] [`hipfort`](https://aur.archlinux.org/packages/hipfort/)
- [x] [`hipify-clang`](https://aur.archlinux.org/packages/hipify-clang/)
- [x] [`openmp-extras`](https://aur.archlinux.org/packages/openmp-extras/)

**Comment by petronny** [comment]
Done. Is there any new change from 4.5.0 to 5.1.3?

PS. The build status and logs of all rocm packages can be found by visiting https://arch4edu.github.io/ and searching for rocm.

**Comment by niobium93** [comment]
`rocm-opencl-runtime` is still out of date. `rocm-hip-runtime` is missing.

**Comment by tpkessler** [comment]
Thank you a lot for your great work @petronny! 

> Is there any new change from 4.5.0 to 5.1.3?

There are some new meta packages:
* [rocm-core](https://aur.archlinux.org/packages/rocm-core)
* [rocm-language-runtime](https://aur.archlinux.org/packages/rocm-language-runtime)
* [rocm-hip-runtime](https://aur.archlinux.org/packages/rocm-hip-runtime)
* [rocm-opencl-sdk](https://aur.archlinux.org/packages/rocm-opencl-sdk)
* [rocm-hip-libraries](https://aur.archlinux.org/packages/rocm-hip-libraries)
* [rocm-hip-sdk](https://aur.archlinux.org/packages/rocm-hip-sdk)

**Comment by petronny** [comment]
@tpkessler 
Hi, I've tried many times to build rocblas but the [build always runs out of the memory](https://github.com/arch4edu/cactus/runs/7382253691?check_suite_focus=true) on a build machine with 16GiB RAM.

Do you have any idea about how much RAM the build actually needs or any workaround?

PS. I've set `_tensile_threads=1`.

**Comment by petronny** [comment]
Done. Please remind me if there is new packages.
