### ISSUE TITLE
Package Request : rocm-hip-sdk,rocm-hip-runtime,rocm-hip-libraries.

### ISSUE THREAD

**Issue by RoARene317** [arch4edu/arch4edu#143]
As you know, HIP is the AMD Translation layer between CUDA and ROCm. Nowadays it's available in AUR but building it took a long and strange amount of time to install it, so I suggest to add this rocm-hip-sdk to arch4edu Repository.

It's now available in AUR Repo: 
https://aur.archlinux.org/packages/rocm-hip-libraries/
https://aur.archlinux.org/packages/rocm-hip-runtime/
https://aur.archlinux.org/packages/rocm-hip-sdk/

**Comment by petronny** [comment]
I'm working on #138 now.
I'll add them when #138 is solved.

**Comment by petronny** [comment]
Now duplicated to #141 , closing.
