### ISSUE TITLE
mxnet needs to be rebuilt

### ISSUE THREAD

**Issue by carlosal1015** [arch4edu/arch4edu#145]
python3.10 is now available, in order to work with python3.10. Now we have `mxnet /usr/lib/python3.9/site-packages/mxnet/__init__.py`, a rebuild will place to `mxnet /usr/lib/python3.10/site-packages/mxnet/__init__.py`.

**Comment by RuRo** [comment]
Can you clarify, why was this issue closed? For example, the latest version of `mxnet-mkl-cuda` (`1.7.0-3`) still seems to be installing itself into `/usr/lib/python3.9`. In fact, most packages from `arch4edu` seem to still be the `python3.9` versions for me.

**Comment by carlosal1015** [comment]
@RuRo there are not too much activity here, I understand the challenge for maintain a repository, the AUR versions is broken also.

**Comment by petronny** [comment]
Hi, I'm dropping mxnet since I never use it. Also I have orphaned it in AUR.

Closing the issue for now.
