### ISSUE TITLE
Package Request: tensorflow-opt-rocm python-tensorflow-opt-rocm 

### ISSUE THREAD

**Issue by tategotoazarasi** [arch4edu/arch4edu#146]
## tensorflow-opt-rocm
- **Introduction:** Library for computation using data flow graphs for scalable machine learning (with ROCM and AVX2 CPU optimizations)
- **Homepage:** https://github.com/rocm-arch/tensorflow-rocm
- **AUR:** https://aur.archlinux.org/tensorflow-rocm.git 

## python-tensorflow-opt-rocm
- **Introduction:** Library for computation using data flow graphs for scalable machine learning (with ROCM and AVX2 CPU optimizations)
- **Homepage:** https://github.com/rocm-arch/tensorflow-rocm
- **AUR:** https://aur.archlinux.org/tensorflow-rocm.git

**Comment by petronny** [comment]
Currently we don't have any server which has CPU with those modern architecture such as Haswell. So we can't compile the `*-opt` packages for now.

But the good news is that now you can help [hosting a build server for arch4edu](https://github.com/arch4edu/arch4edu/wiki/Host-a-build-server-for-arch4edu) to build these packages.

These packages may be packaged in the future if someone can help hosting a build server with modern CPU.

**Comment by petronny** [comment]
We have a builder with newer CPUs to compile the optimized version of tensorflow.

`tensorflow-opt-amd` is just built in https://github.com/arch4edu/cactus/actions/runs/3410665449/jobs/5673897959 .

**Comment by petronny** [comment]
`tensorflow-rocm` is built from https://github.com/tensorflow/tensorflow .
`tensorflow-amd` is built from https://github.com/ROCmSoftwarePlatform/tensorflow-upstream .

**Comment by petronny** [comment]
0fb0783
