### ISSUE TITLE
[Out-of-Date] tensorflow-rocm python-tensorflow-rocm

### ISSUE THREAD

**Issue by tategotoazarasi** [arch4edu/arch4edu#147]
## tensorflow-rocm
https://aur.archlinux.org/packages/tensorflow-rocm/
https://github.com/rocm-arch/tensorflow-rocm
2.4.0-4 => 2.6.0-2

## python-tensorflow-rocm
https://aur.archlinux.org/packages/python-tensorflow-rocm/
https://github.com/rocm-arch/tensorflow-rocm
2.4.0-4 => 2.6.0-2

**Comment by petronny** [comment]
Duplicated with #132
