### ISSUE TITLE
openblas-lapack depends on older libgfortran.so.4

### ISSUE THREAD

**Issue by gururise** [arch4edu/arch4edu#15]
I think openblas-lapack (and possibly many other packages) need to be rebuilt using GCC8 since Arch switched, libgfortran was updated to libgfortran.so.5.  These packages depend on the older libgfortran.so.4 that was in GCC7.

**Comment by petronny** [comment]
I'm rebuilding everything now.
This will take a few days.

**Comment by petronny** [comment]
But I won't bump the pkgrels.
You need to re-installed the package yourself if it is broken.

**Comment by petronny** [comment]
Most of the packages have been rebuilt, expect the followings.
I'm working on them.

- [ ] eclim
- [ ] hdf-java
- [ ] hdf4-java
- [ ] hdf5-openmpi-java
- [ ] octave-general
- [ ] cntk
- [ ] hdfview
- [ ] hdfview-beta
- [ ] mxnet
- [ ] octave-miscellaneous
- [ ] opencv2
- [ ] root
- [ ] root-extra
- [ ] scilab
- [ ] torch7-cunn-git
- [ ] torch7-cunnx-git
- [ ] torch7-rnn-git
