### ISSUE TITLE
qemu-user-static{,-bin} is outdated

### ISSUE THREAD

**Issue by kescherCode** [arch4edu/arch4edu#151]
6.2 is available, arch4edu currently only ships 6.1

**Comment by petronny** [comment]
qemu-user-static-bin is updated. 7cdd3ac73b79310991fdc82facde87d7c12dfa01

But qemu-user-static failed to build. Build log: https://github.com/arch4edu/cactus/actions/runs/2482318858

**Comment by petronny** [comment]
6716b507dd3880e85bf0c3112967edd028e753d6
