### ISSUE TITLE
Openboard: error while loading shared libraries: libpoppler.so.115

### ISSUE THREAD

**Issue by Moltkex** [arch4edu/arch4edu#152]
Hi, 
I installed openboard a while ago from this repo, and it was working fine until just recently when it started giving that error on the title. My guess, is that  **libpoppler** got updated and your pkg 's version (**openboard 1.6.1-14**) doesn't support it, or something like that. This is poppler's version currently installed in the OS: **poppler 22.02.0-2**

**Comment by carlosal1015** [comment]
Work-around
```
$ git clone https://github.com/bartoszek/AUR-openboard.git
$ cd AUR-openboard
$ makepkg -si
```

**Comment by Moltkex** [comment]
> Work-around
> 
> ```
> $ git clone https://github.com/bartoszek/AUR-openboard.git
> $ cd AUR-openboard
> $ makepkg -si
> ```

Will try that. Thanks for your reply.

**Comment by Moltkex** [comment]
@carlosal1015 Thanks! That worked! :+1: :grin: By the way, I'd forgotten, but I did try to install that pkg via AUR with yay. It was taking too long, so I had to stop the process since I needed to use my pc(have bills to pay :joy: ). This time it took a long time too, I guess the CPU doesn't help much :joy:

**Comment by carlosal1015** [comment]
Could you paste on gist.github.com, the output of `makepkg -s 2>&1 | tee log.txt`

**Comment by Moltkex** [comment]
> Could you paste on gist.github.com, the output of `makepkg -s 2>&1 | tee log.txt`

Hmmm ... No sure I understand what you're asking. Do you what me to re-build the pkg and run that?

**Comment by carlosal1015** [comment]
No worries, if the built was successfully, but still failing due to non compatible poppler library, let's wait to be fixed on AUR.

**Comment by Moltkex** [comment]
> No worries, if the built was successfully, but still failing due to non compatible poppler library, let's wait to be fixed on AUR.

Ok. Thanks!

**Comment by Moltkex** [comment]
I removed openboard after it stopped working, now I just reinstalled it again using the same pkg, and it worked! :grin:

**Comment by Moltkex** [comment]
Well, it's stopped working again :disappointed: With a different error, tho; 
```
openboard: error while loading shared libraries: libavformat.so.58: cannot open shared object file: No such file or directory
```
FFmpeg just got updated/upgraded, so ... I'm starting to think this pkg is quite problematic to be used in arch :rofl:

**Comment by carlosal1015** [comment]
Oh @Moltkex, is very common with packages based on shared libraries.
Citing [Arch Wiki](https://wiki.archlinux.org/title/AUR_helpers):
> However, keep in mind that a rebuild of package may be required when its shared library dependencies are updated, not only when the package itself is updated.

Sorry for the bad time, but this happen is not only for openboard.

**Comment by Moltkex** [comment]
@carlosal1015 Yeah, I get it. By the way, openboard is working again. Actually, It was a happy accident :grin: I installed **gimp-plugin-gmic** and noticed some FFmpeg things were installed too, so I thought, could it be? I typed **openboard** in konsole, hit **Enter**, and no errors whatsoever just this warning message ```libpng warning: iCCP: CRC error``` no idea what that is about, but it started and works fine so far. I just hope some near-future update doesn't break it again :rofl:

**Comment by carlosal1015** [comment]
Consider closing this issue @Moltkex .

**Comment by Moltkex** [comment]
> Consider closing this issue @Moltkex .

Yeah, sorry. I sometimes forget I can close these things. By the way, openboard stopped working again, and I honestly just gave up. Thanks for all your help!

**Comment by carlosal1015** [comment]
Oh no, I said because https://aur.archlinux.org/packages/openboard fixed the issue, and arch4edu rebuild two days ago.
