### ISSUE TITLE
python-conda is outdated with AUR

### ISSUE THREAD

**Issue by holymonson** [arch4edu/arch4edu#154]
Version in [AUR](https://aur.archlinux.org/packages/python-conda) is 4.11.0 while 4.10.3 in arch4edu, and it should be built with python 3.10 instead of 3.9.
I doubt if all python packages should be rebuilt.

**Comment by holymonson** [comment]
So is `python-conda-package-handling`

**Comment by petronny** [comment]
3d368346a55190aab7f116335cb56ce885c869b2 5e9a023df667379d4eb2ed75d74924e2b1933767
