### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by adrianinsaval** [arch4edu/arch4edu#161]
the openfoam-org and openfoam-com packages are outdated
gmsh is outdated and fails to launch with missing library error
the paraview-opt package is now not necessary because the one in the main repos installs to opt now and doesn't conflict with vtk anymore

**Comment by adrianinsaval** [comment]
Is this repo abandoned? Looks like there's many outdated package

**Comment by Jirido** [comment]
also this file/bucket are missing
http://s3.amazonaws.com/files.brackets.io/cef/cef_binary_3.2785.1486_linux64_release.zip

**Comment by adrianinsaval** [comment]
and what is that?

**Comment by petronny** [comment]
@adrianinsaval all fixed.
65693ffa2c3e7c4219940aed1f1dcf476e008ea6
d62993b88f13b94adb05e7f5e49b54ea4d2edb25
d6e6c95dc04d86f643ae1a666b9a90416ecdfbee

@Jirido The original brackets is removed from AUR. Please remind me if someone uploads the community version.
