### ISSUE TITLE
pypy-setuptools is now pypy3-setuptools

### ISSUE THREAD

**Issue by carlosal1015** [arch4edu/arch4edu#162]
Hi, [`pypy-setuptools`](https://github.com/arch4edu/arch4edu/blob/master/pypy-setuptools/PKGBUILD) is now [`pypy3-setuptools`](https://aur.archlinux.org/packages/pypy3-setuptools). Will be nice only track the latest one and forget the other.

**Comment by petronny** [comment]
95063eb8a0f80e7504308d86c10cb760aff64a25
