### ISSUE TITLE
python-glob2 moved to [community]

### ISSUE THREAD

**Issue by carlosal1015** [arch4edu/arch4edu#163]
Hi, the package python-glob2 is not anymore on AUR, now in [community](https://archlinux.org/packages/community/x86_64/python-glob2). Maybe have sense ommited [https://github.com/arch4edu/arch4edu/tree/master/any/python-glob2](https://github.com/arch4edu/arch4edu/tree/master/any/python-glob2)

**Comment by petronny** [comment]
Removed. But I haven't implemented the corresponding functions in cactus.
It will take quite a long time to actually remove the package from the pacman repository.
