### ISSUE TITLE
[Out-of-Date] python-requests-cache

### ISSUE THREAD

**Issue by carlosal1015** [arch4edu/arch4edu#165]
Latest version [is not 0.6.4](https://github.com/arch4edu/arch4edu/blob/master/x86_64/python-requests-cache/PKGBUILD), is 0.9.4.

**Comment by petronny** [comment]
24c2093432359a98faa3f08c0a4dc6755450c28f

BTW, you can check the build log from https://arch4edu.github.io/ to see why a package hasn't been updated.

**Comment by carlosal1015** [comment]
Thank you.
