### ISSUE TITLE
amdgpu opencl based on driver 20.45 (for Legacy GCN cards) 

### ISSUE THREAD

**Issue by iamhumanipromise** [arch4edu/arch4edu#170]
Requesting the full ROCM + OpenCL bundle for GCN 1 and 2 cards based on the 20.45 driver (last to include reliable legacy OpenCL support) Of course, /etc/modprobe.d/amdgpu.conf and radeon.conf need the appropriate SI and CIK options so that they load the amdgpu driver instead of radeon driver. 

Honestly, in the best scenario AMD adds all gfx6xx and gfx7xx cards to the current ROCM stack and supports GCN 3 and 4 also. In the reality of today however... it seems a package that duct tapes together all the parts to make them just barely work is the best we can ask for :)

**Comment by petronny** [comment]
Redirected this issue to https://github.com/rocm-arch/rocm-arch/discussions/838 .
