### ISSUE TITLE
Package request: torque

### ISSUE THREAD

**Issue by llity** [arch4edu/arch4edu#173]
Information

Package Name: [torque]
Can it directly run on Linux: [yes]
Can it run on the wine: [not]
Website: [adaptivecomputing.com/cherry-services/moab-nodus-cloud-bursting](https://adaptivecomputing.com/cherry-services/moab-nodus-cloud-bursting/)
Download URL: [adaptivecomputing/torque@6.1.3.h2](https://github.com/adaptivecomputing/torque/tree/6.1.3.h2?rgh-link-date=2022-07-25T04%3A59%3A30Z)
Package description: Resource management system for submitting and controlling jobs on supercomputers, clusters, and grids.
DOI:
Popularity

Number of citations from WOS per year: [e.g. 5.6, N/A]
Research interests in ResearchGate: [e.g. 0.1, N/A]

torque:
https://github.com/adaptivecomputing/torque/tree/6.1.3.h5?rgh-link-date=2022-07-25T11%3A47%3A35Z

**Comment by petronny** [comment]
https://github.com/arch4edu/arch4edu/commit/161fe6f55c1e801dd33357ca2c559a61c91d284f
