### ISSUE TITLE
python3.7 rebuild

### ISSUE THREAD

**Issue by dianlujitao** [arch4edu/arch4edu#18]
以下几个包的pkgbuild更新了，但新的binary一直没有发布：

 * python-dask
 * python-llvmlite
 * python-numba
 * python-scipy-mkl

请检查一下编译状态？

**Comment by petronny** [comment]
嗯，除了这几个

- [ ] caffe-git
- [ ] cntk
- [ ] gmsh
- [ ] mayavi-py3
- [ ] pocketsphinx
- [ ] pythia
- [ ] python-keras
- [ ] python-librosa
- [ ] python-llvmlite
- [ ] python-numba
- [ ] python-resampy
- [ ] python-scipy-mkl
- [ ] python-slugify
- [ ] python-vtk
- [ ] sphinxbase
- [ ] vtk-py3-qt4

这些也都需要rebuild，正在解决

**Comment by petronny** [comment]
CNTK is waiting for the official response.
https://github.com/Microsoft/CNTK/issues/3354

**Comment by petronny** [comment]
vtk in [community] will be switched to python3. (Now in [testing].)
mayavi-py3 and vtk-py3-qt4 may not needed anymore.
python-vtk is out of date and is waiting for the response of the AUR maintainer.

**Comment by petronny** [comment]
dropped python2-scipy-mkl for now.
And python-scipy-mkl is rebuilt.

**Comment by dianlujitao** [comment]
`python-pydotplus` 似乎也需要rebuild

```
$ pacman -Qqo /usr/lib/python3.6 
python-pydotplus
```

**Comment by petronny** [comment]
嗯，估计是之前误操作产生的回滚的遗留问题

**Comment by petronny** [comment]
https://twitter.com/arch4edu/status/1152096981399064576
