### ISSUE TITLE
Some rocm packages may need to rebuild against fmt 9

### ISSUE THREAD

**Issue by petronny** [arch4edu/arch4edu#180]
Forwarded from [twitter](https://twitter.com/carlosjcheco/status/1576570758113153025).

**Comment by petronny** [comment]
```sh
$ grep fmt x86_64/rocm/*/PKGBUILD
x86_64/rocm/python-pytorch-rocm/PKGBUILD:        "${pkgname}-fmt::git+https://github.com/fmtlib/fmt.git"
x86_64/rocm/python-pytorch-rocm/PKGBUILD:  git config submodule."third_party/fmt".url "${srcdir}/${pkgname}"-fmt
x86_64/rocm/rocsolver/PKGBUILD:depends=('hip' 'rocblas' 'fmt')
```
So there is rocsolver. Is there more?

**Comment by Baguettedood** [comment]
I noticed `python-pytorch-rocm` requires rebuilding too (Pytorch does have an official ROCm build but that doesn't work with gfx803).

**Comment by prurigro** [comment]
It looks like rocsolver doesn't currently build against fmt 9

**Comment by petronny** [comment]
94b5d81260077e8d195242253e23e128a0a04f75
