### ISSUE TITLE
python-pytorch-rocm needs rebuild

### ISSUE THREAD

**Issue by AlukardBF** [arch4edu/arch4edu#183]
Tried to import torch in python, got the following:
```python
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: libroctx64.so.1: cannot open shared object file: No such file or directory
```
/opt/rocm/lib contains only libroctx64.so.4 after recent update to 5.3.0, i guess. If I understand correctly, pytorch needs to be rebuilt against new rocm?

**Comment by petronny** [comment]
Yes. But I think rocm 5.3.0 is still in process since rocm-arch team hasn't announced it yet.
I'll trigger the rebuild when it's done.

And I'm updating our build system to automatically detect such issue. So it may trigger the rebuild before I do.

**Comment by exentio** [comment]
Got any update on the matter? It would be great if you could provide some kind of archive of the previous version in the meantime, I'm having some issues with Stable Diffusion that might or might not be related to this (here, if anyone can help: [https://www.reddit.com/r/StableDiffusion/comments/yalvxz](https://www.reddit.com/r/StableDiffusion/comments/yalvxz))

**Comment by petronny** [comment]
> And I'm updating our build system to automatically detect such kind of issues.

Well, this one may need a few more weeks. I'm triggering the rebuild now.

**Comment by qifei9** [comment]
it seems the rebuild failed: https://github.com/arch4edu/cactus/actions/runs/3310102094

**Comment by petronny** [comment]
> it seems the rebuild failed: https://github.com/arch4edu/cactus/actions/runs/3310102094

Yes, the self-hosted x86_64 builder is in China and suffers from terrible internet connection these days.

**Comment by petronny** [comment]
In the latest build (https://github.com/arch4edu/cactus/actions/runs/3310102094 attempt 16) gets this error:
```
/usr/bin/ld: lib/libc10.so: undefined reference to `google::glog_internal_namespace_::IsGoogleLoggingInitialized()'^M
collect2: error: ld returned 1 exit status
```

**Comment by petronny** [comment]
After 28 times of retries, we finally have python-pytorch-rocm rebuilt https://github.com/arch4edu/arch4edu/commit/473f8bcb9eacd277f5270242dafaaae3796693db , in which most of them failed with network issues. Hmm.
