### ISSUE TITLE
Package request: real version of PETSc

### ISSUE THREAD

**Issue by Rapti** [arch4edu/arch4edu#187]
Right now, arch4edu only offers petsc-complex, which has some downsides and can even cause errors when solving real-number problems with FEniCSx: https://fenicsproject.discourse.group/t/sudden-arity-mismatch-when-defining-non-linear-problem/8844
It would be great to also have the real version of petsc. I believe that the majority of the problems which users are trying to solve don't involve complex numbers anyway.

**Comment by carlosal1015** [comment]
Thank you @Rapti for take a look the issue. I would like first make some tests or look if in the PKGBUILD only use PETSc real version or both as now.

**Comment by carlosal1015** [comment]
[I confirm that the code is not working with complex scalars.](https://asciinema.org/a/535806).
I will start running tests in the PKGBUILD for the FEniCS suite.

**Comment by carlosal1015** [comment]
Hi @Rapti, [two days ago `dolfinx` `0.6.0` was released](https://github.com/FEniCS/dolfinx/releases/tag/v0.6.0) and [from now on the `dolfinx` and `python-fenics-dolfinx` packages are built with the (real scalars) `petsc` package](https://github.com/arch4edu/arch4edu/commit/bbbfdf0f386cf3c74f3e61dbff51b2f61214ce83).

If you get a chance to try more code, please let us know. I will try with the demo code.
