### ISSUE TITLE
loadcaffe problem

### ISSUE THREAD

**Issue by Wulfsta** [arch4edu/arch4edu#19]
I think loadcaffe needs to be rebuilt against the new protobuf:

```
luajit: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/loadcaffe/ffi.lua:10: libprotobuf.so.15: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in function 'error'
	/usr/share/lua/5.1/trepl/init.lua:389: in function 'require'
	neural_style.lua:6: in main chunk
	[C]: in function 'dofile'
	/usr/bin/th:150: in main chunk
	[C]: at 0x00404680
```

**Comment by petronny** [comment]
loadcaffe-git has been rebuilt.
Please check if it works now.

**Comment by Wulfsta** [comment]
Now getting:
```
luajit: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/cutorch/init.lua:2: cannot load '/usr/lib/lua/5.1/libcutorch.so'
stack traceback:
	[C]: in function 'error'
	/usr/share/lua/5.1/trepl/init.lua:389: in function 'require'
	neural_style.lua:327: in function 'setup_gpu'
	neural_style.lua:53: in function 'main'
	neural_style.lua:601: in main chunk
	[C]: in function 'dofile'
	/usr/bin/th:150: in main chunk
	[C]: at 0x00404680
```

**Comment by petronny** [comment]
```sh
$ pacman -Fyo /usr/lib/lua/5.1/libcutorch.so
usr/lib/lua/5.1/libcutorch.so is owned by arch4edu/torch7-cutorch-git r1026.5e9d86c-1
```
Do you have `torch7-cutorch-git` installed?

**Comment by petronny** [comment]
I'm trying to find out why `torch7-cutorch-git` is needed here.
It's not in the dependencies and may be incorrectly added by arch4edu.
Arch4edu will try to enable all optional dependencies for every package.
It may cause this situation.

**Comment by petronny** [comment]
Well, I looked into it but I have no idea why it linked to `/usr/lib/lua/5.1/libcutorch.so`.
So I will just leave it there until nobody is using this package.

According to pkgstats, there are still 36 of 20560 guys are using `loadcaffe-git`, 
and 126 guys are using `torch7-git`.

I will drop `loadcaffe-git` when there are only 10 guys using it and the entire torch things when there are only 10 guys using `torch7-git`.
