### ISSUE TITLE
Request to add MeshLab and CloudCompare packages

### ISSUE THREAD

**Issue by cybaol** [arch4edu/arch4edu#199]
Hi bro, `MeshLab` and `CloudCompare` are widely used in Computer Vision fields such as point cloud processing and SLAM (Simultaneous Localization And Mapping).
MeshLab: `https://aur.archlinux.org/packages/meshlab`
CloudCompare: `https://aur.archlinux.org/packages/cloudcompare`

**Comment by petronny** [comment]
https://github.com/arch4edu/arch4edu/commit/3536611c12b2c9b370eb06a3c6db75f062103048

**Comment by petronny** [comment]
https://github.com/bartoszek/AUR-cloudcompare/issues/18

**Comment by petronny** [comment]
https://github.com/arch4edu/arch4edu/commit/9b334b303e1908fe1c0dd00343a4a7172bb6aea1
