### ISSUE TITLE
请求收录scilab beta版本

### ISSUE THREAD

**Issue by Bangjie** [arch4edu/arch4edu#2]
请问能包含scilab 的beta版本: Scilab 6.0.0 beta 2 吗? 可以将其命名为scilab-beta，与scilab5.5.2区分。

**Comment by petronny** [comment]
我打算添加scilab-git算了，不过尚有一些依赖包不在aur中，正在慢慢添加
另外我比较好奇为什么要用beta版的呢？有什么比较吸引的新功能呢？

**Comment by Bangjie** [comment]
因为aur装scilab-git没成功过。实在是麻烦了

**Comment by petronny** [comment]
scilab-git由于lucene的api变更编译不成功
我最后还是做了一个叫scilab-beta-bin的包，请明天试试有什么问题没。。
