### ISSUE TITLE
 Package request: vvc-vtm

### ISSUE THREAD

**Issue by Freed-Wu** [arch4edu/arch4edu#200]
<https://aur.archlinux.org/packages/vvc-vtm> VVC (aka H266) is the latest video encoding standard reference software. H265 reference software has been included by the archlinux community repository. So can we add H266 before Archlinux include it?

Thanks! And can this repo has a github issue template like <https://github.com/termux/termux-packages/tree/master/.github/iSSUE_TEMPLATE>?

**Comment by petronny** [comment]
4b423e8b61684ba107c21509cf46a524df860940
