### ISSUE TITLE
arch4edu keybase mirror is not reachable

### ISSUE THREAD

**Issue by t3pfaffe** [arch4edu/arch4edu#201]
Getting pacman errors with this mirror:
`error: failed retrieving file 'arch4edu.db' from arch4edu.keybase.pub : The requested URL returned error: 504
error: failed to synchronize all databases (failed to retrieve some files)`

**Comment by petronny** [comment]
```sh
$ curl https://arch4edu.keybase.pub/x86_64/arch4edu.db > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  662k  100  662k    0     0  98849      0  0:00:06  0:00:06 --:--:--  142k
```
Sometime the keybase mirror is not responsive. Please keep retrying or use another mirror.

PS. You can rank the mirrors with
```sh
rankmirrors -r arch4edu mirrorlist.arch4edu
```
