### ISSUE TITLE
Yet another mirror in Germany

### ISSUE THREAD

**Issue by SunRed** [arch4edu/arch4edu#204]
I have this mirror running for quite a while now and was recently reminded again to finally contribute my mirror to this project.

* Location: Germany
* Organization: Manuel Hüsers
* URL: `https://mirror.sunred.org/arch4edu`

I check every 5 minutes for an update using the timestamp in the `lastupdate` file on the origin server, so the mirror should be quite closely synced without unnecessary syncs of the entire directory. The script used is a modified version of the [template](https://gitlab.archlinux.org/archlinux/infrastructure/-/blob/master/roles/syncrepo/files/syncrepo-template.sh) from the Arch Linux Project.
Additionally there are 8 sync slots open for syncing with `rsync` and `rsync-ssl` using `rsync://sync.mirror.sunred.org/arch4edu`. I may put the main domain behind a caching reverse proxy at some point, hence the use of a different domain for the sync endpoint.

**Comment by petronny** [comment]
Thank you very much for providing the new mirror!

https://github.com/arch4edu/mirrorlist/commit/bf51f510e6367dd0a7b99bdd59d677b231a10b5e
