### ISSUE TITLE
Package Request: mkl-dnn

### ISSUE THREAD

**Issue by enihcam** [arch4edu/arch4edu#21]
Intel(R) Math Kernel Library for Deep Neural Networks (Intel(R) MKL-DNN) is an open-source performance library for deep-learning applications. The library accelerates deep-learning applications and frameworks on Intel architecture. Intel MKL-DNN contains vectorized and threaded building blocks that you can use to implement deep neural networks (DNN) with C and C++ interfaces.

Given that most modern Intel processors support MKL acceleration, and `python-numpy-mkl` and `python-scipy-mkl` already exist in arch4edu, it should be reasonable to add 'mkl-dnn' as well.

'mkl-dnn':
https://github.com/intel/mkl-dnn
https://aur.archlinux.org/packages/mkl-dnn

**Comment by petronny** [comment]
7afa1d6944b8443c120bea03b6036b66f7c367f5
