### ISSUE TITLE
Stellarium: Broken gpsd dependencies

### ISSUE THREAD

**Issue by EdWoow** [arch4edu/arch4edu#211]
It seems, the arch4edu repo stellarium binary does not honor the latest update of gpsd:

[2023-01-12T09:31:54+0100] [ALPM] upgraded gpsd (3.24-1 -> 3.25-1)

$ stellarium 
stellarium: error while loading shared libraries: libgps.so.29: cannot open shared object file: No such file or directory

$ pacman -Ql gpsd | grep libgps.so
gpsd /usr/lib/libgps.so
gpsd /usr/lib/libgps.so.30
gpsd /usr/lib/libgps.so.30.0.0

$ pacman -Qs stellarium
local/stellarium 1.2-1
    Software which renders realistic skies in real time with OpenGL

**Comment by petronny** [comment]
https://github.com/arch4edu/cactus/actions/runs/3938893278

**Comment by petronny** [comment]
cca0e091e0274049dc99dbb97333824b40e53154
