### ISSUE TITLE
Request to ignition-cmake-2 and ignition-math-6 package

### ISSUE THREAD

**Issue by cybaol** [arch4edu/arch4edu#213]
I notice that `gazebo` must build with `ignition-math-6`( latest version 6.13.0)  and `ignition-cmake-2`( latest version 2.16.0). But these dependency packages are not in AUR.  Current latest dependencies in AUR are `ignition-math`(version 7.1.0) and `ignition-cmake`(version 3.0.1).

**Comment by petronny** [comment]
https://github.com/acxz/gazebo-arch/issues/46

**Comment by petronny** [comment]
Thanks for the information.

I believe @acxz will add these packages to AUR if they are necessary.

I'll keep an eye on this issue.

**Comment by petronny** [comment]
377ed35e8a3f1621bc045ee1ee2f8252f8abd5de
91a5c4d358f845ee410e286e108a385b056847ba
