### ISSUE TITLE
Update of libindi breaks Stellarium

### ISSUE THREAD

**Issue by EdWoow** [arch4edu/arch4edu#214]
arch update libindiclient.so.1 -> libindiclient.so.2 breaks stellarium

$ stellarium 
stellarium: error while loading shared libraries: libindiclient.so.1: cannot open shared object file: No such file or directory

$ find /usr/lib -iname "*libindiclient*"
/usr/lib/libindiclient.so.2
/usr/lib/libindiclient.so

**Comment by petronny** [comment]
Forward from @carlosal1015 in telegram.

> This issue is related with https://aur.archlinux.org/packages/stellarium#comment-900257
> Is not fixed by upstream yet.

**Comment by GaVenga** [comment]
I fixed it by softlinking: /usr/lib/libindiclient.so.2.0.0 → /usr/lib/libindiclient.so.1
(sudo ln -s /usr/lib/libindiclient.so.2.0.0  /usr/lib/libindiclient.so.1)
Only do this when **downgraded** library is needed!
(Example: actual Version is "2" - needed version is "1" - not actual "3" to needed "4")

**Comment by EdWoow** [comment]
Thanks very much for your work! Stellarium works again as of today

Am 27.03.23 um 17:57 schrieb Oromion:

**Comment by carlosal1015** [comment]
> Thanks very much for your work! Stellarium works again as of today Am 27.03.23 um 17:57 schrieb Oromion:
Great!
