### ISSUE TITLE
pcl build error still exists

### ISSUE THREAD

**Issue by cybaol** [arch4edu/arch4edu#215]
pcl build error still exists at https://github.com/arch4edu/cactus/actions/runs/4103840902/jobs/7080552061

**Comment by cybaol** [comment]
I don't know if that's the reason.
https://blog.csdn.net/boshuzhang/article/details/103663480

**Comment by petronny** [comment]
> I don't know if that's the reason.
https://blog.csdn.net/boshuzhang/article/details/103663480

It says out of memory. It might be. I'll try the self-hosted builder.

**Comment by petronny** [comment]
https://github.com/arch4edu/arch4edu/commit/f02801b7ab222644539298d6ea2038bbae9f7e85

**Comment by cybaol** [comment]
Why `pcl-debug` is built?  It's so big .

**Comment by petronny** [comment]
https://gitlab.archlinux.org/archlinux/devtools/-/commit/b64d8ebacf8268e986bde912cff839311ac74fa8

I'm working on it.

**Comment by petronny** [comment]
https://github.com/arch4edu/cactus/commit/6c5764dc696d8ef0b5e23f6ee88b2859c21172f4

https://github.com/arch4edu/cactus/actions/runs/4131511687/jobs/7139220717
