### ISSUE TITLE
US Mirror down

### ISSUE THREAD

**Issue by HalJordan** [arch4edu/arch4edu#216]
Are there no other options in the US?

error: failed retrieving file 'arch4edu.db' from arch4edu.keybase.pub : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed to synchronize all databases (download library error)

**Comment by petronny** [comment]
Sorry we don't have other mirrors in US. You may want to try the other mirrors.
You can rank the mirrors by speed with:
```
rankmirrors -r arch4edu /etc/pacman.d/mirrorlist.arch4edu
```
----
Also related: #175

**Comment by petronny** [comment]
Hi, we are testing a new global mirror at https://repository.arch4edu.org.

**Comment by petronny** [comment]
> has been down for a while now, too apparently

Fixed now. Thanks for the report.
