### ISSUE TITLE
ros-noetic-desktop-full: conflicting files in gazebo and ignition-tools

### ISSUE THREAD

**Issue by muasim** [arch4edu/arch4edu#218]
File /usr/bin/gz exists in  **ignition-tools-2.0.0-1-any** and **gazebo-11.12.0-4-x86_64**.

Therefore it fails with this message:

`error: failed to commit transaction (conflicting files)`
`/usr/bin/gz exists in both 'ignition-tools' and 'gazebo'`

**Comment by petronny** [comment]
https://github.com/acxz/gazebo-arch/issues/51

**Comment by petronny** [comment]
This one should be solved with recently built gazebo packages. Please wait for them to be synchronized to the mirrors.

However, `ros-noetic-pcl-ros` still fails to build. https://github.com/ros-noetic-arch/ros-noetic-pcl-ros/issues/9

**Comment by cybaol** [comment]
> 



> This one should be solved with recently built gazebo packages. Please wait for them to be synchronized to the mirrors.
> 
> However, `ros-noetic-pcl-ros` still fails to build. [ros-noetic-arch/ros-noetic-pcl-ros#9](https://github.com/ros-noetic-arch/ros-noetic-pcl-ros/issues/9)

Add the dependency package `qhull`(optional in `pcl`) to fix it.

**Comment by petronny** [comment]
> Add the dependency package qhull(optional in pcl) to fix it.

Thanks! Now `ros-noetic-pcl-ros` is built. I will run another scan for broken links when the package is published into the repository.

[13f7144](https://github.com/arch4edu/arch4edu/commit/13f7144607913c044bf07da5197ae317bbe6cc33)

**Comment by cybaol** [comment]
`ros-noetic-desktop-full` needs to rebuild because of python 3.11

**Comment by petronny** [comment]
All ros-noetic has been rebuilt against python 3.11 (#229) and passed the link scan check. Please test if everything works.
