### ISSUE TITLE
ROS Humble needs to be rebuilt for Python 3.11

### ISSUE THREAD

**Issue by pryre** [arch4edu/arch4edu#227]
The current version seems to be built against Python3.10, Arch core has updated to Python3.11. Runtime error suggests that rclpy cannot find Python3.10 libraries anymore (which I believe is correct as they do not exist).

- [Link to related documentation](https://docs.ros.org/en/humble/How-To-Guides/Installation-Troubleshooting.html#import-failing-without-library-present-on-the-system)

- Runtime Error:
```
Failed to load entry point 'list': No module named 'rclpy._rclpy_pybind11'
The C extension '/opt/ros/humble/lib/python3.10/site-packages/_rclpy_pybind11.cpython-311-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://docs.ros.org/en/humble/Guides/Installation-Troubleshooting.html#import-failing-without-library-present-on-the-system' for possible solutions
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.5', 'console_scripts', 'ros2')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 50, in main
    add_subparsers_on_demand(
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/command/__init__.py", line 250, in add_subparsers_on_demand
    extension.add_arguments(
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2topic/command/topic.py", line 29, in add_arguments
    add_subparsers_on_demand(
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/command/__init__.py", line 237, in add_subparsers_on_demand
    extension = command_extensions[name]
                ~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'list'

```

**Comment by pryre** [comment]
Managed to rebuild the package myself, no major set-backs. Looks like there's an upstream update from [pybind11_vendor](https://github.com/ros2/pybind11_vendor/) that was required to be pulled (either that or I just missed it when I cloned the repo.

Had a few other instances of missing `#include <cstdint>` and `#include <stdexception>` in a few C++ packages, but that might be something on my end.

**Comment by petronny** [comment]
Hi, would you like to share your modified PKGBUILD so we can build it for everyone?

**Comment by pryre** [comment]
Good idea. I'll put the required changes into a patch and make sure everything is up to date with rolling. Give me a day or two and I'll make a pull request.

**Comment by petronny** [comment]
Thanks in advanced! It's also OK to just upload the PKGBUILD to here or somewhere if you are not familiar with `cactus.yaml`.

**Comment by pryre** [comment]
Had a good dig into this today. My attempt can be found on [my branch](https://github.com/pryre/arch4edu/commit/e0301b6b5ca01de43d9113a1600e1fa1b6751ed7). See PKGBUILDs and patches attached, prefixed with their parent packages. I have not had any experience with cactus, so thanks for that! -- Apologies that they are `.txt`, GitHub would not have accepted the raw files.

[ros2-humble_PKGBUILD.txt](https://github.com/arch4edu/arch4edu/files/11642028/ros2-humble_PKGBUILD.txt)
[ros-humble_python_11_support.patch.txt](https://github.com/arch4edu/arch4edu/files/11642029/ros-humble_python_11_support.patch.txt)
[ros-arch-deps_PKGBUILD.txt](https://github.com/arch4edu/arch4edu/files/11642030/ros-arch-deps_PKGBUILD.txt)

The major change was actually working around the SIP4 issues. The current state of SIP from PyQt/riverbankcomputing is a bit of a mess, and a lot of the ROS packages are stuck on SIP4 on ubuntu (even for their rolling branch?). It seems that the PyQt group are trying to push people along, but there's been a slow uptake.

The only way I could get this to build effectively with my knowledge of SIP was to drop it entirely and switch to the pyside2 bindings. If anyone knows their way around PyQt better, then this can probably be avoided. I personally don't see the downside, but I would guess that there is licensing issues, etc. Apologies if this is not sufficient, and good luck to anyone that needs to fix that mess properly.

**Comment by pryre** [comment]
From further investigation of the `python_qt_bindings` package, they are looking to depreciate this eventually package anyway, so it may be a non-issue in the future, or for the next major ROS2 release:
[https://github.com/ros-visualization/python_qt_binding/pull/117](https://github.com/ros-visualization/python_qt_binding/pull/117).

Also noted that the longer term fix has had a pull request waiting for a few years now ([https://github.com/ros-visualization/python_qt_binding/pull/94](https://github.com/ros-visualization/python_qt_binding/pull/94)). I imagine that the ros-visualization group is a bit under-powered as of late. Guess we'll see how this pans out.

**Comment by AchmadFathoni** [comment]
I managed to build humble in clean chroot using https://github.com/m2-farzan/ros2-humble-PKGBUILD/pull/11.

**Comment by petronny** [comment]
5088c72c22c297dc3b4ffb23b96a4beca7cd64e5
