### ISSUE TITLE
Python 3.11 rebuild

### ISSUE THREAD

**Issue by petronny** [arch4edu/arch4edu#229]
### Containing files under `/usr/lib/python3.10/site-packages/`
```sh
$ pacman -Fq "/usr/lib/python3.10/site-packages/" | awk -F/ '$1 == "arch4edu" { print "* [ ] " $2 }' 
```
* [x] ceph-octopus-libs
* [x] ceph-pacific-libs
* [x] code_saturne
* [x] libsearpc
* [x] mavproxy
* [x] ~~opengv-git~~ (dropped)
* [x] pastix
* [x] python-apex-git
* [x] ~~python-dumux~~ (merged in dumux)
* [x] ~~python-dune-common~~ (merged in dune-common)
* [x] ~~python-dune-geometry~~ (merged in dune-geometry)
* [x] ~~python-dune-grid~~ (merged in dune-grid)
* [x] ~~python-dune-istl~~ (merged in dune-istl)
* [x] ~~python-dune-localfunctions~~ (merged in dune-localfunctions)
* [x] python-fenics-dolfinx
* [x] ~~python-glog~~ (dropped)
* [x] python-gpustat
* [x] python-jax
* [x] python-jaxlib
* [x] ~~python-llvmlite~~ (no longer in AUR, now in `[extra]`)
* [x] python-mkl-fft
* [x] python-mkl-random
* [x] python-mkl-service
* [x] python-ml-dtypes
* [x] ~~python-ninja-syntax~~ (dropped)
* [x] python-nvidia-ml-py
* [x] python-property-cached
* [x] ~~python-pysynphot~~ (dropped)
* [x] python-ray
* [x] python-scikit-image
* [x] ~~python-tensorflow-amd~~ (dropped)
* [x] ~~python-tensorflow-opt-amd~~ (dropped)
* [x] python-tifffile

### Containing files under `/opt/ros/humble/lib/python3.10/site-packages/`
```sh
$ pacman -Fq "/opt/ros/humble/lib/python3.10/site-packages/" | awk -F/ '$1 == "arch4edu" { print "* [ ] " $2 }'
```
* [x] ros2-humble (#227)

### Containing files under `/opt/ros/noetic/lib/python3.10/site-packages/`
```sh
$ pacman -Fq "/opt/ros/noetic/lib/python3.10/site-packages/" | awk -F/ '$1 == "arch4edu" { print "* [ ] " $2 }'
```

* [x] ros-noetic-actionlib
* [x] ros-noetic-actionlib-msgs
* [x] ros-noetic-actionlib-tutorials
* [x] ros-noetic-angles
* [x] ros-noetic-bond
* [x] ros-noetic-bondpy
* [x] ros-noetic-camera-calibration
* [x] ros-noetic-camera-calibration-parsers
* [x] ros-noetic-catkin
* [x] ros-noetic-compressed-depth-image-transport
* [x] ros-noetic-compressed-image-transport
* [x] ros-noetic-control-msgs
* [x] ros-noetic-control-toolbox
* [x] ros-noetic-controller-manager
* [x] ros-noetic-controller-manager-msgs
* [x] ros-noetic-cv-bridge
* [x] ros-noetic-diagnostic-analysis
* [x] ros-noetic-diagnostic-common-diagnostics
* [x] ros-noetic-diagnostic-msgs
* [x] ros-noetic-diagnostic-updater
* [x] ros-noetic-diff-drive-controller
* [x] ros-noetic-dynamic-reconfigure
* [x] ros-noetic-gazebo-msgs
* [x] ros-noetic-gazebo-plugins
* [x] ros-noetic-gazebo-ros
* [x] ros-noetic-gencpp
* [x] ros-noetic-geneus
* [x] ros-noetic-genlisp
* [x] ros-noetic-genmsg
* [x] ros-noetic-gennodejs
* [x] ros-noetic-genpy
* [x] ros-noetic-geographic-msgs
* [x] ros-noetic-geometry-msgs
* [x] ros-noetic-image-geometry
* [x] ros-noetic-image-proc
* [x] ros-noetic-image-publisher
* [x] ros-noetic-image-rotate
* [x] ros-noetic-image-view
* [x] ros-noetic-interactive-markers
* [x] ros-noetic-joint-state-publisher
* [x] ros-noetic-kdl-parser-py
* [x] ros-noetic-laser-assembler
* [x] ros-noetic-laser-filters
* [x] ros-noetic-laser-geometry
* [x] ros-noetic-map-msgs
* [x] ros-noetic-mavros
* [x] ros-noetic-message-filters
* [x] ros-noetic-nav-msgs
* [x] ros-noetic-nodelet       
* [x] ros-noetic-nodelet-topic-tools    
* [x] ros-noetic-pcl-msgs        
* [x] ros-noetic-pcl-ros     
* [x] ros-noetic-polled-camera    
* [x] ros-noetic-python-qt-binding    
* [x] ros-noetic-qt-dotgraph      
* [x] ros-noetic-qt-gui            
* [x] ros-noetic-qt-gui-cpp         
* [x] ros-noetic-qt-gui-py-common       
* [x] ros-noetic-resource-retriever    
* [x] ros-noetic-rosbag                
* [x] ros-noetic-rosboost-cfg           
* [x] ros-noetic-rosclean    
* [x] ros-noetic-roscpp                
* [x] ros-noetic-roscpp-tutorials    
* [x] ros-noetic-roscreate    
* [x] ros-noetic-rosgraph-msgs    
* [x] ros-noetic-roslaunch    
* [x] ros-noetic-roslib       
* [x] ros-noetic-roslint    
* [x] ros-noetic-roslz4    
* [x] ros-noetic-rosmake        
* [x] ros-noetic-rosmaster     
* [x] ros-noetic-rosmsg    
* [x] ros-noetic-rosnode       
* [x] ros-noetic-rosparam     
* [x] ros-noetic-rospy     
* [x] ros-noetic-rospy-tutorials
* [x] ros-noetic-rosservice
* [x] ros-noetic-rostest
* [x] ros-noetic-rostopic
* [x] ros-noetic-rosunit
* [x] ros-noetic-roswtf      
* [x] ros-noetic-rqt-action
* [x] ros-noetic-rqt-bag
* [x] ros-noetic-rqt-bag-plugins
* [x] ros-noetic-rqt-console
* [x] ros-noetic-rqt-dep  
* [x] ros-noetic-rqt-graph
* [x] ros-noetic-rqt-gui
* [x] ros-noetic-rqt-gui-py
* [x] ros-noetic-rqt-image-view
* [x] ros-noetic-rqt-launch   
* [x] ros-noetic-rqt-logger-level
* [x] ros-noetic-rqt-moveit
* [x] ros-noetic-rqt-msg
* [x] ros-noetic-rqt-nav-view
* [x] ros-noetic-rqt-plot
* [x] ros-noetic-rqt-pose-view
* [x] ros-noetic-rqt-publisher
* [x] ros-noetic-rqt-py-common
* [x] ros-noetic-rqt-py-console
* [x] ros-noetic-rqt-reconfigure
* [x] ros-noetic-rqt-robot-dashboard
* [x] ros-noetic-rqt-robot-monitor
* [x] ros-noetic-rqt-robot-steering
* [x] ros-noetic-rqt-runtime-monitor
* [x] ros-noetic-rqt-rviz
* [x] ros-noetic-rqt-service-caller
* [x] ros-noetic-rqt-shell
* [x] ros-noetic-rqt-srv
* [x] ros-noetic-rqt-tf-tree
* [x] ros-noetic-rqt-top
* [x] ros-noetic-rqt-topic
* [x] ros-noetic-rqt-web
* [x] ros-noetic-rviz
* [x] ros-noetic-sensor-msgs
* [x] ros-noetic-shape-msgs
* [x] ros-noetic-smach
* [x] ros-noetic-smach-msgs
* [x] ros-noetic-smach-ros
* [x] ros-noetic-smclib
* [x] ros-noetic-std-msgs
* [x] ros-noetic-std-srvs
* [x] ros-noetic-stereo-image-proc
* [x] ros-noetic-stereo-msgs
* [x] ros-noetic-tf-conversions
* [x] ros-noetic-tf2-geometry-msgs
* [x] ros-noetic-tf2-kdl
* [x] ros-noetic-tf2-msgs
* [x] ros-noetic-tf2-py
* [x] ros-noetic-tf2-ros
* [x] ros-noetic-theora-image-transport
* [x] ros-noetic-topic-tools
* [x] ros-noetic-trajectory-msgs
* [x] ros-noetic-turtle-actionlib
* [x] ros-noetic-turtlesim
* [x] ros-noetic-urdfdom-py
* [x] ros-noetic-uuid-msgs
* [x] ros-noetic-visualization-msgs
* [x] ros-noetic-xacro

**Comment by lsr0** [comment]
Many `ros-noetic-*` packages would also need rebuild.
