### ISSUE TITLE
Mismatching cuda version for pytorch and torchvision

### ISSUE THREAD

**Issue by Awlexus** [arch4edu/arch4edu#230]
I'm getting the following error when trying to launch [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui), after following the [wiki on how to install and run on AMD GPUs with ROCM](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs#install-on-amd-and-arch-linux)
```
$ TORCH_COMMAND='pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.1.1' PYTORCH_HIP_ALLOC_CONF=max_split_size_mb:512 python launch.py --no-half --theme dark --listen --skip-torch-cuda-test

RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
```
I've installed the following packages:
* extra/python-pytorch-rocm 2.0.1-2 
* arch4edu/torchvision-rocm 0.15.1-5

I'm sorry if this issue is misplaced, I wasn't exactly sure where exactly to post it

**Comment by petronny** [comment]
> following the [wiki on how to install and run on AMD GPUs with ROCM](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs#install-on-amd-and-arch-linux)'

Hi, do you mean you have run exactly the following commands?

```sh
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
cd stable-diffusion-webui
python -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip wheel

# It's possible that you don't need "--precision full", dropping "--no-half" however crashes my drivers
TORCH_COMMAND='pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.1.1' python launch.py --precision full --no-half
```

If so, then you are creating a virtual environment and installing the prebuilt pytorch and torchvision from pypi inside it.
None of `extra/python-pytorch-rocm` or `arch4edu/torchvision-rocm` will be loaded inside the virtual environment.

If you do want to use the `extra/python-pytorch-rocm` and `arch4edu/torchvision-rocm` which are installed in the system environment, the simplest way is just not to use the virtual environment like:

```sh
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
cd stable-diffusion-webui

# It's possible that you don't need "--precision full", dropping "--no-half" however crashes my drivers
python launch.py --precision full --no-half
```

If `launch.py` shows any missing libraries, install it via pacman, or `pip install --user` which install things to `~/.local/lib/python3.11`.

PS. I don't have an AMD GPU and I don't have interest with Stable Diffusion so I can't gurantee that the above guide is 100% correct.

**Comment by Awlexus** [comment]
Hi, I didn't know that about the venv. I tried it now without venv and I was able to start it. Thanks for your help!
