### ISSUE TITLE
Package request: devilutionx devilutionx-voices fheroes2 gzdoom rustdesk-bin vcmi ventoy-bin woeusb-ng xonotic for aarch64

### ISSUE THREAD

**Issue by petronny** [arch4edu/arch4edu#245]
Forwarded from the telegram group. https://github.com/7Ji/archrepo/issues/12

- [x] devilutionx https://aur.archlinux.org/packages/devilutionx
- [x] fheroes2 https://aur.archlinux.org/packages/fheroes2 
- [x] gzdoom https://aur.archlinux.org/packages/gzdoom 
- [x] lzdoom https://aur.archlinux.org/packages/lzdoom 
- [x] rustdesk-appimage https://aur.archlinux.org/packages/rustdesk-appimage
- [x] vcmi https://aur.archlinux.org/packages/vcmi 
- [x] ventoy-bin
- [x] woeusb-ng https://aur.archlinux.org/packages/woeusb-ng
- [x] xonotic https://archlinux.org/packages/extra/x86_64/xonotic/

**Comment by petronny** [comment]
@DragonSerW Hi, I'm adding these packages to arch4edu but I need some information.

For devilutionx, fheroes2, gzdoom, vcmi, I assume these are open source remakes of existing games. Distributing the remaked binaries is ok but I guess we won't get the permission to distribute any texture and data from the original game. Please check if these packages contain any texture and data from the original game.

For xonotic, is there any progress on adding this to the official archlinuxarm repository?

**Comment by DragonSerW** [comment]
I need no textures, because I already bought all these games and have all shareware media in my g*g-com account :-)
About Xonotic: I will ask for it @ archlinuxarm.

**Comment by petronny** [comment]
> I need no textures, because I already bought all these games and have all shareware media in my g*g-com account :-)

That's the right way. But I still need to ensure that no original data is shipped inside these packages.

If you already have these packages installed on your machine, please test if they can run without downloading the original game from your account. If not installed, I'll try building them once and please test them when they are built.

**Comment by DragonSerW** [comment]
They are free/libre for sure and all of them require original game data.

**Comment by DragonSerW** [comment]
Hello petronny!
Please add `lzdoom-bin` (https://aur.archlinux.org/packages/lzdoom-bin, as I can understand it).
Do not know, which one is proper, lzdoom or lzdoom-bin.
