### ISSUE TITLE
Package Request: AUR Package localai-git - Local OpenAI API replacement running on CPU,CUDA,ROCM

### ISSUE THREAD

**Issue by wuxxin** [arch4edu/arch4edu#247]
## LocalAI

The free, Open Source OpenAI alternative. Self-hosted, community-driven and local-first. Drop-in replacement for OpenAI running on consumer-grade hardware

- Aur
  - https://aur.archlinux.org/packages/localai-git
  - https://github.com/wuxxin/aur-packages/tree/main/localai-git
- Upstream
  - https://github.com/mudler/LocalAI

currently only the cpu version builds,

i have a ROCM/AMD version already running locally (this would need the rocm builder), CUDA should be possible too

**Comment by wuxxin** [comment]
next version should work, probably with cuda too.

**Comment by wuxxin** [comment]
(next next) :grin:

**Comment by petronny** [comment]
ba21ab7ca86cee36fba8a1c1b4446a5bd96cebae

**Comment by wuxxin** [comment]
thank you, i will add ROCM once working, but it currently breaks because of weird flags while compiling
