### ISSUE TITLE
build localai-git: System.IO.IOException: No space left on device

### ISSUE THREAD

**Issue by wuxxin** [arch4edu/arch4edu#249]
since ~ 2 runs, probably the huge size of both cuda and rocm sdk, see https://github.com/arch4edu/cactus/actions/runs/7151231768

if needed you can split the pkg build using _ENABLE_CUDA=0 or 1 and _ENABLE_ROCM=0 or 1 so the makedepends also are only for one of CUDA or ROCM

**Comment by petronny** [comment]
be462930af597a4f48bb10e84d6878fadf12e908

We can built it with the unsafe builder which provides ~20GiB more space.

However, the build fails with
```
clang++: error: no input files
/bin/sh: line 1: gfx906: command not found
/bin/sh: line 1: gfx908: command not found
/bin/sh: line 1: gfx90a: command not found
/bin/sh: line 1: gfx1030: command not found
/bin/sh: line 1: gfx1100: command not found
/bin/sh: line 1: gfx1101: command not found
/bin/sh: line 1: gfx1102: command not found
make[1]: *** [Makefile:230: ggml-cuda.o] Error 127
```
https://github.com/arch4edu/cactus/actions/runs/7123897218/job/19553156043

**Comment by wuxxin** [comment]
added a fix, next version should build with all selected gfx architectures
