### ISSUE TITLE
python-graphviz is out of date

### ISSUE THREAD

**Issue by hubutui** [arch4edu/arch4edu#25]
The latest release is 0.10.1, https://github.com/xflr6/graphviz/releases/tag/0.10.1.

**Comment by petronny** [comment]
fcfd8a6a7d4bce3c5d8a9bbd60533a94584b54a2

https://mirrors.tuna.tsinghua.edu.cn/arch4edu/x86_64/python-graphviz-0.10.1-1-any.pkg.tar.xz

去年就更细了啊

**Comment by petronny** [comment]
我知道了，之前有一次any包的整理，那时候老的和新的的顺序传反了
