### ISSUE TITLE
packaging error: intel-parallel-studio-xe

### ISSUE THREAD

**Issue by lizr2004** [arch4edu/arch4edu#27]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* intel-compiler-base
* intel-common-libs （疑似不存在）
* intel-openmp （疑似不存在）
----

从 `intel-compiler-base=2019.2.187-1` 升级到 `intel-compiler-base=2019.3.199-3` 发现新的包依赖 `intel-common-libs=2019.3.199` `intel-openmp=2019.3.199` 而他们在旧版本中并不存在，在源目录 (tuna mirror arch4edu) 中也没有找到。貌似是 lilac 的 auto update 85034d12 引起的。谢谢！

**Comment by lizr2004** [comment]
对不起，刚刚看到 741b530，确认没问题会 close issue 的。不过这好像得等 tuna sync。

**Comment by petronny** [comment]
Fixed

**Comment by lizr2004** [comment]
Fixed
