### ISSUE TITLE
heasoft needs inetutils

### ISSUE THREAD

**Issue by Firestar-Reimu** [arch4edu/arch4edu#272]
when installing heasoft, it tells me:

```bash
source /etc/profile.d/heasoft.sh and initialize heasoft before use:

$ heainit
OR
$ source "${HEADAS}/headas-init.sh"
```

but when I run `heainit`:

```bash
$ heainit
/opt/heasoft/x86_64-pc-linux-gnu-libc2.39/BUILD_DIR/headas-setup: line 338: hostname: command not found
```

Archlinux needs `inetutils` to provide `hostname` command, and this is listed in the AUR page:

https://aur.archlinux.org/packages/heasoft

**Comment by petronny** [comment]
3f438dd

**Comment by Firestar-Reimu** [comment]
OK, after I run:

```
source /etc/profile.d/heasoft.sh and initialize heasoft before use:

heainit
```

I can use `xspec` now!

**Comment by Firestar-Reimu** [comment]
But I cannot find heasoftpy whether in my system python or anaconda. I cannot run `import heasoftpy` or `hpyupdate`

https://heasarc.gsfc.nasa.gov/lheasoft/heasoftpy/
