### ISSUE TITLE
out of date package, python-cupy

### ISSUE THREAD

**Issue by Shengyis** [arch4edu/arch4edu#273]
since numpy is 2.0 now, the current python-cupy version 13.1.0-2 seems not compatible with nunpy 2.0, I can not import cupy any more, it will give 
AttributeError: module 'numpy' has no attribute 'AxisError

the latest version of python-cupy is 13.2

**Comment by petronny** [comment]
9719cc36b2f6bd26295e596750a8d0ee985de11f
