### ISSUE TITLE
community-testing 收录了 caffe2

### ISSUE THREAD

**Issue by hubutui** [arch4edu/arch4edu#29]
see https://www.archlinux.org/packages/community-testing/x86_64/caffe2-cuda/

**Comment by petronny** [comment]
嗯，等待进入community之后会drop

**Comment by hubutui** [comment]
不过 pytorch 和 caffe2 不是冲突的么？看样子TU还没有解决好这个问题．see https://bugs.archlinux.org/task/62617

**Comment by hubutui** [comment]
pytorch 1.1 已经进 community 了，但是 caffe2 没有，它俩的冲突似乎没有解决．caffe2 直接删掉了．
