### ISSUE TITLE
Package request: miniforge

### ISSUE THREAD

**Issue by carlosal1015** [arch4edu/arch4edu#292]
Replace mambaforge with https://aur.archlinux.org/packages/miniforge because it was [removed](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/NADUO37ETXC66OBUFQ4GQQWVEJZDBV2I/#IRQUXKUGQRLXV73OV7NXL3FJVVUKGRJH).

#265

**Comment by holymonson** [comment]
@carlosal1015 Could you remove mambaforge as well? It has been removed on AUR. 
And you may want to add `replaces=(mambaforge)` in your miniforge PKGBUILD.

**Comment by carlosal1015** [comment]
Done https://github.com/arch4edu/arch4edu/commit/c2920a1324aaf092b47a7cfdd9a8591977ae965c
