### ISSUE TITLE
请求收录root 和 root-extra

### ISSUE THREAD

**Issue by Bangjie** [arch4edu/arch4edu#3]
root 是欧洲核子中心(CERN)开发的基于LGPL2.1协议的数据分析软件。广泛应用于高能物理、加速器物理、同步辐射实验或仿真的数据处理。
AUR中将root拆分成[root](https://aur.archlinux.org/packages/root/) 和[root-extra](https://aur.archlinux.org/packages/root-extra/)两个包。由于编译量有点大，依赖有点多。。。。如果方便的话，请收录这两个包。
万分感谢。

PS. [ROOT-Mirror on github](https://github.com/root-mirror/root) and [ROOT Homepage](https://root.cern.ch).

**Comment by petronny** [comment]
WIP

**Comment by petronny** [comment]
这两个包已经添加了，请等待tuna同步

**Comment by Bangjie** [comment]
万分感谢。
