### ISSUE TITLE
关于 mkl-dnn 打包的疑问

### ISSUE THREAD

**Issue by hubutui** [arch4edu/arch4edu#31]
mkl-dnn 打包的时候使用了 mklml，而 mklml 是 mkl 的一个子集，里面包含了 `libiomp5.so`，也就是造成 `openmp` 文件冲突的源头．我看 mkl-dnn 并没有说一定要在链接的时候使用 mklml 的，可以直接用 gcc 或者 openmp 的 OpenMP 实现．这样就不会有文件冲突了．

**Comment by petronny** [comment]
请先去AUR反馈/讨论一下吧，如果他们没回复这里再做处理

**Comment by huyizheng** [comment]
之前版本的pkgbuild如果删掉source里的mklml同时也删掉prepare里的相关部分，在电脑上安装了intel-mkl的相关包的情况下，可以正常编译并且不会有文件冲突。
但这样做的话也许这个包就得加上intel-mkl的依赖了。

**Comment by petronny** [comment]
本来也应该有intel-mkl依赖吧，都叫mkl-dnn了

**Comment by hubutui** [comment]
下一个版本的 mkl-dnn 就不再依赖 mkl/mklml 了．如果有包依赖到 mkl/mklml 的话是需要另外打包的，而且的话，mkl/mklml 不是开源的，也没有说可以任意分发的吧．

**Comment by petronny** [comment]
mkl-dnn 就是 mklml 的升级版吧

**Comment by hubutui** [comment]
不能这么说吧，mklml 是 mkl 的一个子集，mkl 不开源，到底 mkl-dnn 重用了 mkl 的多少代码我们估计无从知晓．但是 1.0 版本以前的 mkl-dnn 可以链接到 mkl 来提速，但是能提的恐怕不多吧．1.0 版本这不是已经准备不再默认链接到 mkl 了嘛．也有可能是考虑到许可证的问题．

**Comment by petronny** [comment]
b75c920bbfbef48f3e597d3acca21b2e1d14e2ef
1.0 了，这个问题解决了么？

**Comment by hubutui** [comment]
没有问题了．
