### ISSUE TITLE
[Vote] R support

### ISSUE THREAD

**Issue by petronny** [arch4edu/arch4edu#32]
I have a plan to add R packages into arch4edu such as `r-devtools`, `r-jsonlite`.

But:
1. Although pkgstats says 14.58% of arch users have r installed, I rarely know guys that actually use it.
1. Some of the R packages are orphaned and maybe not well-maintained in AUR.
1. I don't use R at all so I wish they can be maintained by other maintainers who are using them.

So I post this issue as a vote or survey before starting to add them.

If there are enough votes that requring the R packages, we will start to do it.

**Comment by SamLukeYes** [comment]
Building JASP would need some R packages. https://github.com/archlinuxcn/repo/issues/2231

**Comment by petronny** [comment]
`jasp-desktop` needs 481 dependencies in AUR.

I'll think about writing a script to automatically import them from AUR.

**Comment by petronny** [comment]
Added. But apparently I can't maintain such amount of packages.
So if you are using or interested in these packages.
Please the check their build logs at https://arch4edu.github.io/ and help maintaining these packages.

**Comment by starsareintherose** [comment]
I think you would better to say contribute to [bioarchlinux](https://github.com/BioArchLinux/Packages), these packages maintained by BioArchLinux and we fix the bug and push them to the AUR

**Comment by petronny** [comment]
Yeah, that will also work.
If you find a package is maintained by the BioArchLinuxBot on AUR, you can also contact the bioarchlinux group to fix it.

**Comment by petronny** [comment]
Also I’m thinking about adding r support to aarch64.
Please comment here if you need it on aarch64.

**Comment by starsareintherose** [comment]
> Also I’m thinking about adding r support to aarch64. Please comment here if you need it on aarch64.

As of now, we have no plans to do so unless there is a massive and unprecedented increase in ARM users

**Comment by starsareintherose** [comment]
Thanks, but I don't think that GitHub action is continuous and reliable service and there is no huge need for ARM.
