### ISSUE TITLE
Package Request: jabref

### ISSUE THREAD

**Issue by machsix** [arch4edu/arch4edu#35]
Jabref is a citation manager, and bibtex editor. It eases the work of creating `bib` file for publication. All you need is to provide `doi` number and it can generates `bib` file automatically.

The official website is https://www.jabref.org. There is already an AUR package https://aur.archlinux.org/packages/jabref/.

The software is licensed with MIT. So theoretically, we should be able to do anything with it?

**Comment by petronny** [comment]
https://twitter.com/arch4edu/status/1156041382752137216
