### ISSUE TITLE
Package Request: lammps

### ISSUE THREAD

**Issue by physkets** [arch4edu/arch4edu#36]
LAMMPS, or the Large-scale Atomic/Molecular Massively Parallel Simulator is a software package that lets you perform molecular dynamics simulations, and various other related analyses.

URL: https://lammps.sandia.gov/

I currently maintain its stable, beta and git packges in the aur. It would be nice if you folks could build and host the binaries of the stable version:  
https://aur.archlinux.org/packages/lammps/

This is the beta version, in case you want to take a look:
https://aur.archlinux.org/packages/lammps-beta/

**Comment by petronny** [comment]
https://twitter.com/arch4edu/status/1161463237143121922
