### ISSUE TITLE
nvidia-docker /etc/docker/daemon.json 文件冲突

### ISSUE THREAD

**Issue by lilydjwg** [arch4edu/arch4edu#38]
这个配置文件里我配置了镜像，于是安装 nvidia-docker 的时候它就冲突了。另外它没有写在 backup 里，是不是意味着我卸载 nvidia-docker 的时候我自己的配置也没了？

如果 docker 无法把这个配置分文件处理的话，建议使用安装脚本来处理这个配置文件的更改。

**Comment by petronny** [comment]
```
This package is now deprecated in upstream, as you can now use nvidia-container-toolkit together with docker 19.03's new native GPU support.
```

所以改装nvidia-container-toolkit和原版docker就好了？

**Comment by lilydjwg** [comment]
哦哦。我先看看怎么用。

**Comment by lilydjwg** [comment]
好了～然而用完之后N卡关不了了……
