### ISSUE TITLE
Package Request: mayavi-py3, python-vtk

### ISSUE THREAD

**Issue by Chao-zhi** [arch4edu/arch4edu#4]
These two package can help to creating 3D graphics by python, it often be used as visualization in scientific computing by python.

**Comment by petronny** [comment]
WIP

**Comment by petronny** [comment]
Added.
But the PKGBUILDs of mayavi-py3 and its dependency vtk-py3-qt4 has undetermined dependencies.
I have patched them to make them complied, but may need more patches to make them work.
Please report to this page if you get errors.

**Comment by petronny** [comment]
mayavi in [community] has moved to Python 3.
So we don't need mayavi-py3 anymore :)
