### ISSUE TITLE
Unrecognized archive format error with the keybase.pub mirror

### ISSUE THREAD

**Issue by lmwang9527** [arch4edu/arch4edu#42]
After I added the keybase.pub mirror to my /etc/pacman.conf following [these steps](https://github.com/arch4edu/arch4edu/wiki/Add-arch4edu-to-your-Archlinux), I am getting "error: could not open file /var/lib/pacman/sync/arch4edu.db: Unrecognized archive format" when running pacman:

```
$ sudo pacman -Syyu
:: Synchronizing package databases...
 core                                              133.4 KiB   494K/s 00:00 [###] 100%
 extra                                            1646.2 KiB  5.36M/s 00:00 [###] 100%
 community                                           4.9 MiB  8.22M/s 00:01 [###] 100%
 arch4edu                                            7.3 KiB  0.00B/s 00:00 [###] 100%
:: Starting full system upgrade...
error: could not open file /var/lib/pacman/sync/arch4edu.db: Unrecognized archive format
```

This is the section of my /etc/pacman.conf
```
[arch4edu]
Server = https://keybase.pub/arch4edu/$arch
```

And I am not getting the error if I use the mirror https://mirrors.tuna.tsinghua.edu.cn/arch4edu/$arch

Is there a problem with the keybase mirror or did I do something wrong? Thanks!

**Comment by petronny** [comment]
There does be difference between the tuna and keybase mirror, since symbolic link doesn't work properly in keybase. I'll take a look at it.

**Comment by petronny** [comment]
Hi, the mirror link need to be changed to
```
https://arch4edu.keybase.pub/$arch
```
I've also updated the wiki page. Sorry for the mistake.

**Comment by lmwang9527** [comment]
It works. Thanks!
