### ISSUE TITLE
rebuild r-mkl with the latest version of intel-mkl and intel-common-libs

### ISSUE THREAD

**Issue by lmwang9527** [arch4edu/arch4edu#43]
r-mkl-3.6.1-1-x86_64.pkg.tar.xz currently on the repository was built with mkl 2019.4.243. However, when installing r-mkl with pacman, it will install intel-mkl-2019.5.281 and intel-common-libs-2019.5.281 as dependencies because they are the latest version. This causes installing certain R packages to fail since options in /etc/R/Makeconf still point to /opt/intel/compilers_and_libraries_2019.4.243/linux/mkl/include, which doesn't exist.

Can you please rebuild r-mkl with the latest intel-mkl and intel-common-libs to fix this? 

Thanks!

**Comment by petronny** [comment]
27c3482b422bc45ecaa494733ed303dd24e21da6

But it may need a few days to actually do the rebuild. Now it's building some monsters.

You will get the updating message from our Telegram/Twitter/Weibo channel.

**Comment by petronny** [comment]
https://twitter.com/arch4edu/status/1185408377175842816

**Comment by lmwang9527** [comment]
Thanks!
