### ISSUE TITLE
[Request] `ros-melodic-desktop-full` Robot Operating System (ROS)

### ISSUE THREAD

**Issue by acxz** [arch4edu/arch4edu#44]
Hello,
First off thank you for hosting these packages.

I would like to request a package and it's dependencies for this repository.
`ros-melodic-desktop-full` is the latest version of the Robot Operating System. (https://www.ros.org/) It is very prominent in the robotics community and it would definitely be a nice addition to have for this repository. There are a couple packages like `gazebo`, `ogre-1.9`, and `pcl` which take forever to compile and installers of ROS-melodic on Arch, all feel the pain. As such having binaries for these PKGBUILDs would be lovely.

Thank you

**Comment by acxz** [comment]
Thank you for working on this, makes me really happy!
I will go ahead and add the wiki link for adding this repository to the ROS installation page (https://wiki.ros.org/melodic/Installation/ArchLinux) so that users know about this repository and can leverage it when installing ROS.

**Comment by acxz** [comment]
See the updated ROS Melodic installation page (https://wiki.ros.org/melodic/Installation/ArchLinux#preview), I have added your repository to the instructions before installing ROS.

**Comment by petronny** [comment]
Thank you. The packages may need a few days to build and enter the repository. Stay tuned for our Telegram/Twitter/Weibo channel.

**Comment by acxz** [comment]
I hope this repository gets more exposure by adding ROS and linking it from the official install page.

**Comment by petronny** [comment]
Packages like `ros-melodic-roscpp` shouldn't have `arch=('any')`.

`any` here means once built, the output package suits for any architecture.
But packages like the cpp stuffs are not, they only suit the architecture that the build machine uses.

You have to list all architectures like `arch=('x86_64' 'armv6h' 'armv7h' 'aarch64')`.

**Comment by acxz** [comment]
Ah I was not aware of this, I'll go ahead and bring this issue up with the Arch ros maintainers and let you know when it is fixed. Thank you.

**Comment by petronny** [comment]
Any updates?

If not I will manually set `arch=('x86_64')` for all `ros-melodic-*` packages.
And all the packages will then be built for x86_64 only. Is that fine?

**Comment by acxz** [comment]
Ah no. Sorry about that. The maintainer has mentioned he will go through the packages and add the architectures via a script but he has not done that yet. 

I think getting something out is better than nothing, so if you could do that that would be much much appreciated!

**Comment by acxz** [comment]
Here is the continued conversation: https://github.com/ros-melodic-arch/ros-melodic-roscpp/issues/2
Also tagging @bionade24

**Comment by bionade24** [comment]
Done now, sorry for letting this hanging so long. https://github.com/ros-melodic-arch/ros-melodic-roscpp/issues/2 But please wait a week as explained in the other issue, because I'll try to get the "standard" packages into community repo.

**Comment by acxz** [comment]
@bionade24 it has been a week, what is the status? Can @petronny continue taking up this request?

**Comment by bionade24** [comment]
No, sadly I haven't had time for doing this, as one paper came in between and I was focusing on it. Now I'm currently in holidays, so expect at least another week. Currently my Repo should have most of the packages.

**Comment by acxz** [comment]
@bionade24 Is there some way for us to follow the conversation you are having with the TU's about getting these pacakges in the main repos?

**Comment by acxz** [comment]
@bionade24 Sorry to ping u about this issue again, but has there been any progress? I know you have your own repo for the ROS packages, but I would like to see it in the official repos (ideally) or in a repo that more people use such as this one.

**Comment by bionade24** [comment]
Sorry, I haven't had time for doing this.

**Comment by acxz** [comment]
Now that ros-noetic is around the corner and we have started packaging for it, I would like to rescind the request for ros-melodic-* packages. Note some deps will still be common such as gazebo, pcl, ogre, etc. But the ros-melodic-* packages will be changed to ros-noetic-*.

If someone else would like ros-melodic-* packages to be packaged by arch4edu please comment on this thread to reopen the issue.

**Comment by thecountoftuscany** [comment]
ROS Melodic is still the long term support version of ROS that is widely being used by people in the academia. I personally would like for ros-melodic-* packages to be made available with arch4edu because I use it (and plan to use it till the next LTS release), but I also understand that this is a volunteer effort and it may not be possible. Thanks in any case!

**Comment by acxz** [comment]
@thecountoftuscany when you “plan to use it till the next LTS release” you do realize that next LTS release noetic is being released on May 23rd, right?

**Comment by thecountoftuscany** [comment]
@acxz I did not realise that. This makes sense. Thanks!

**Comment by bionade24** [comment]
@thecountoftuscany Even though I have not much time, I'll still care about melodic until I'll drop ROS completely, which will be ~ 1 year in the future.
