### ISSUE TITLE
unable to synchronize data base

### ISSUE THREAD

**Issue by M0l0ch0** [arch4edu/arch4edu#47]
I followed the instructions and got the error when I run pacman -Syy. How can i solve?, Sorry if here isn't the right place for the poblem.

**Comment by petronny** [comment]
Could you paste the log of your error here?

**Comment by M0l0ch0** [comment]
Sorry, this is the error:
error: failed retrieving file 'Arch4Edu.db' from mirrors.pinganyun.com : The requested URL returned error: 404 
error: failed to update Arch4Edu (failed to retrieve some files) 
error: failed to synchronize all databases 

Synchronizing databases... (pkgfile -u)

error: failed to update repo: Arch4Edu

**Comment by petronny** [comment]
I guess you mis-typed
```
[arch4edu]
Server = <the mirror site you choose>
```
to
```
[Arch4Edu]
Server = <the mirror site you choose>
```
in `/etc/pacman.conf`.

**Comment by M0l0ch0** [comment]
Worked. Thank you!. :). Excuse me for this fool error.
