### ISSUE TITLE
r-mkl needs recompiling

### ISSUE THREAD

**Issue by meriops** [arch4edu/arch4edu#48]
I think r-mkl needs recompiling, following the update of package icu to v65 on Nov. 14th, 2019. Otherwise, r-mkl does not find libicu.so, because it's looking for the previous version.

**Comment by meriops** [comment]
For some reason, if I install intel-mkl and r-mkl from arch4edu, the linker is looking for libicuuc.so.64 and libicui18n.so.64 and cannot find them since the system has version 65 of these files. I'm not really sure if I'm doing something wrong or what...

**Comment by petronny** [comment]
@meriops You are doing right. We are rebuilding `r-mkl` but it needs a few more days.

I will reply here when it's rebuilt.

**Comment by petronny** [comment]
It has been rebuilt.
But the version of the package is same. You need to re-install the package manually.
