### ISSUE TITLE
python-scipy-mkl not working

### ISSUE THREAD

**Issue by iyanmv** [arch4edu/arch4edu#53]
When I try to import `scipy.integrate.quad` I get the following error:

```
$ python
>> from scipy.integrate import quad
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/scipy/integrate/__init__.py", line 94, in <module>
    from ._ode import *
  File "/usr/lib/python3.8/site-packages/scipy/integrate/_ode.py", line 92, in <module>
    from . import vode as _vode
ImportError: /usr/lib/python3.8/site-packages/scipy/integrate/vode.cpython-38-x86_64-linux-gnu.so: invalid ELF header
```
Exactly same happen to me when I compile the package using the PKGBUILD from AUR (see [this comment](https://aur.archlinux.org/packages/python-scipy-mkl/#comment-723662)).

Any ideas why? With `python-scipy` from Arch repos I don't have that problem.

**Comment by petronny** [comment]
I've checked this file. And it's definitely broken. (Most bytes of this file is empty)
I'll try to find out how this happens.
But now my build server is down. Please wait a few days to let it recover.

**Comment by petronny** [comment]
The package is rebuilt with the latest gcc headers. 111c49b0bb17dfa11bc5a060c1f71c83bbcaa1d1

And it seems that this issue is also fixed in this rebuild.
Please test it and feel free to report any another issues.

**Comment by iyanmv** [comment]
Perfect! It is working fine now, thanks!
