### ISSUE TITLE
ros-melodic needs to build against latest boost

### ISSUE THREAD

**Issue by thecountoftuscany** [arch4edu/arch4edu#59]
I recently discovered that after an upgrade on arch linux, `roscore` dies with this message:
```
... logging to /home/<username>/.ros/log/8d25acce-602b-11ea-989a-3c77e67a89d5/roslaunch-arch-20630.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://arch:45109/
ros_comm version 1.14.3


SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES

auto-starting new master
process[master]: started with pid [20638]
ROS_MASTER_URI=http://arch:11311/

setting /run_id to 8d25acce-602b-11ea-989a-3c77e67a89d5
process[rosout-1]: started with pid [20648]
/opt/ros/melodic/lib/rosout/rosout: error while loading shared libraries: libboost_thread.so.1.71.0: cannot open shared object file: No such file or directory
started core service [/rosout]
[rosout-1] process has died [pid 20648, exit code 127, cmd /opt/ros/melodic/lib/rosout/rosout __name:=rosout __log:=/home/nishant/.ros/log/8d25acce-602b-11ea-989a-3c77e67a89d5/rosout-1.log].
log file: /home/nishant/.ros/log/8d25acce-602b-11ea-989a-3c77e67a89d5/rosout-1*.log
[rosout-1] restarting process
process[rosout-1]: started with pid [20653]
/opt/ros/melodic/lib/rosout/rosout: error while loading shared libraries: libboost_thread.so.1.71.0: cannot open shared object file: No such file or directory
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

Looking in `/usr/lib/` I found that I had the following files:
```
libboost_thread.so
libboost_thread.so.1
libboost_thread.so.1.72
libboost_thread.so.1.72.0
```
but not `libboost_thread.so.1.71.0`. Is there a way to make this work?

**Comment by petronny** [comment]
Hi, I've updated the configurations for the related packages in arch4edu.
We'll get new packages that build against the latest boost as soon as they are built successfully.

If the new packages don't work, it means there are still other ros packages built against the old boost. I can update their configurations too if you can find them out.

**Comment by thecountoftuscany** [comment]
Hi, thanks for the fix!
I updated the system with the new `ros-melodic-cpp-common` and `ros-melodic-rostime` packages but still have the same error. I found [this page](index.ros.org/d/boost) which lists all packages that depend on boost. Adding a screenshot here for reference
![image](https://user-images.githubusercontent.com/14308382/76169864-cab34d80-6139-11ea-8793-c38e4dd8901c.png)
Hope this helps!

**Comment by petronny** [comment]
Hi,
the rest packages haven't been added into arch4edu yet. (See also #44 )

For now, you may want to build the related packages yourself.

**Comment by acxz** [comment]
@petronny I think this issue can be closed

**Comment by thecountoftuscany** [comment]
I just added a comment on https://github.com/arch4edu/arch4edu/issues/44 about this issue (https://github.com/arch4edu/arch4edu/issues/44#issuecomment-626276862). But please feel free to close this if you think that that is appropriate. Thanks!

**Comment by petronny** [comment]
I'm migrating ros-melodic to ros-noetic.

Re-open this issue when this issue happens to ros-noetic. (I'm sure it will ...)
