### ISSUE TITLE
Package Request: openfoam,gmsh

### ISSUE THREAD

**Issue by Helmholts** [arch4edu/arch4edu#6]
openfoam
The open source CFD toolbox，
http://www.openfoam.org
https://github.com/OpenFOAM
The AUR links:
https://aur.archlinux.org/packages/openfoam/
https://aur.archlinux.org/packages/openfoam2.4-git/
https://aur.archlinux.org/packages/openfoam3.0-git/
openfoam开源的计算流体力学软件，有个非官方软件源
home_Minerva_W_Science_Arch_Extra    
Maintainer:    
Description: OpenFOAM packages.
[home_Minerva_W_Science_Arch_Extra]
Server = http://download.opensuse.org/repositories/home:/Minerva_W:/Science/Arch_Extra/$arch 

gmsh
A free 3D finite element grid generator with a build-in CAD engine and post-processor
计算流体力学的网格划分软件
http://gmsh.info/
AUR:https://aur.archlinux.org/packages/gmsh-bin/

**Comment by petronny** [comment]
为什么是gmsh-bin而不是gmsh呢？

**Comment by Helmholts** [comment]
> 为什么是gmsh-bin而不是gmsh呢？


根据评论
> lahwaacz 在 2017-04-13 09:44 发表了评论 
>The PKGBUILD hardcodes an explicit (and now outdated) python version:
>install -D -m644 "${pkgdir}/usr/bin/onelab.py" "${pkgdir}/usr/lib/python3.5/site-packages/onelab.py" 

gmsh的PKGBUILD好像不能正常运行。
如果可以添加gmsh，就不用考虑gmsh-bin了。

**Comment by petronny** [comment]
这个错误应该已经被修复了

**Comment by petronny** [comment]
gmsh和openfoam的所有依赖已经添加。
openfoam现在是一个孤儿包，并且感觉PKGBUILD写的不好
我正在联系openfoam 2/3的maintainer接管openfoam

另外openfoam的2,3,4三代的差异很大吗，都需要添加进arch4edu吗？

**Comment by Helmholts** [comment]
> openfoam的2,3,4三代的差异很大吗，都需要添加进arch4edu吗？

各代在包含组件、模拟模型、求解方案等方面有差异，可以看发行注记：
https://openfoam.org/release/3-0-1/
https://openfoam.org/release/4-1/
https://openfoam.org/release/2-4-0/

如果不好全部添加，希望添加上3代

**Comment by petronny** [comment]
2,3代已经添加，4代aur上的pkgbuild编译失败，正在尝试修改

**Comment by petronny** [comment]
4代已经修复，请等待自动build
