### ISSUE TITLE
[Request] `rocm-dkms` and `rocm-libs` (ROCm) Radeon Open Compute Software

### ISSUE THREAD

**Issue by acxz** [arch4edu/arch4edu#60]
Hello once again @petronny!

I'm back to request another package group. Recently I have started to work on GPGPU and I have been packaging ROCm (AMD's version of CUDA) for ArchLinux along with other contributors here: https://github.com/rocm-arch/rocm-arch

We have recently made decent enough progress where we are comfortable in requesting these packages to be packaged under this repository, (there still might be some issues tho, lol).

Anyway there are a couple PKGBUILDs that take forever to build and install (particularly `llvm-amdgpu`). If the metapackage `rocm-dkms` and `rocm-libs` can be included in this repository it would definitely be appreciated!

Thanks once again, and do take care!

**Comment by petronny** [comment]
Hi, I've added `rocm-dev`.
But about `rocm-dkms`, I notice that it depends on itself. Is that right?

**Comment by acxz** [comment]
Ah `rocm-dkms` depends on `rock-dkms` notice the difference in `rocm` and `rock`, weird and confusing but that is how AMD does it.

**Comment by petronny** [comment]
`rocm-libs` involves:
- [ ] hipblas
- [ ] hipcub
- [ ] hipsparse
- [ ] rocalution
- [ ] rocblas
- [ ] rocfft
- [ ] rocprim
- [ ] rocrand
- [ ] rocsparse
- [ ] rocthrust

**Comment by petronny** [comment]
@acxz Many dependencies of `rocm-libs` depend on `rocm-comgr`. Should it be replaced by `comgr`?

**Comment by acxz** [comment]
Yeah... I would say right now to hold off on packages that require `rocm-comgr` until we get that dep removed from all the packages. It should be done once https://github.com/rocm-arch/rocm-arch/issues/124 is closed.

**Comment by petronny** [comment]
We have `rocm-dkms` now.
Let me know if `rocm-libs` is ready to build.

**Comment by acxz** [comment]
Nice! Most of rocm-Libs is ready besides 1 or 2 packages that still need to be synced, so that rocm-comgr is removed from the deps of those packages. Feel free to start packaging the ones that do not require rocm-comgr as of right now.

**Comment by acxz** [comment]
@petronny we got our packages synced up, if you could start packaging the rocm-libs deps that would be great!

**Comment by petronny** [comment]
Finally, `rocm-libs` is built.

**Comment by acxz** [comment]
Thanks so much @petronny 
Really mean it, doing some great work here.
