### ISSUE TITLE
Discusstion about orphaning qgis-git

### ISSUE THREAD

**Issue by petronny** [arch4edu/arch4edu#61]
To @heavysink :

qgis-git is building failed for a long time. The latest successful build is `3.10.0_master.r59259.c2cde01cc8-1` and it's even older than qgis's version `3.12.0-1`.

And according to pkgstats, the usages of qgis and qgis-git are `376 / 15819 = 2.38%` and `4 / 15819 = 0.03%`. It means that only `4 / 380 = 1.1%` qgis users are using qgis-git.

Do we really need qgis-git?

**Comment by heavysink** [comment]
I have removed qgis-git, but it seems that qgis at the repo is not working due to undefined symbol...
