### ISSUE TITLE
ros-melodic-angles is out of date

### ISSUE THREAD

**Issue by KomaGR** [arch4edu/arch4edu#63]
Similar to #62. `ros-melodic-angles` installs in a python location from previous python versions. May need a rebuild with latest version of python.

**Comment by petronny** [comment]
About this package, its PKGBUILD specified some configurations about python 3.7.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ros-melodic-angles#n52
Please also report this to its AUR maintainers.

**Comment by jwhendy** [comment]
Nearly our whole repository has these paths hardcoded in. We have an issue that lists out all of `ros-melodic-*` that actually uses them. This is not one of those packages. This is the issue:
```
$ tar -xvf ros-melodic-angles-1.9.11-2-any.pkg.tar.xz 
.BUILDINFO
.MTREE
.PKGINFO
opt/
opt/ros/
opt/ros/melodic/
opt/ros/melodic/include/
opt/ros/melodic/include/angles/
opt/ros/melodic/include/angles/angles.h
opt/ros/melodic/lib/
opt/ros/melodic/lib/pkgconfig/
opt/ros/melodic/lib/pkgconfig/angles.pc
opt/ros/melodic/lib/python3.7/
opt/ros/melodic/lib/python3.7/site-packages/
opt/ros/melodic/lib/python3.7/site-packages/angles/
opt/ros/melodic/lib/python3.7/site-packages/angles-1.9.11-py3.7.egg-info
opt/ros/melodic/lib/python3.7/site-packages/angles/__init__.py
opt/ros/melodic/lib/python3.7/site-packages/angles/__pycache__/
opt/ros/melodic/lib/python3.7/site-packages/angles/__pycache__/__init__.cpython-37.pyc
opt/ros/melodic/share/
opt/ros/melodic/share/angles/
opt/ros/melodic/share/angles/cmake/
opt/ros/melodic/share/angles/cmake/anglesConfig-version.cmake
opt/ros/melodic/share/angles/cmake/anglesConfig.cmake
opt/ros/melodic/share/angles/package.xml
```
Your build system built against a `python3.7` system and hasn't re-built. You're shipping with `python3.7` paths; it has nothing to do with our PKGBUILD. If you build this, it will install wherever `python3.x` lives, regardless of it's `3.7` or `3.8`.

As further proof, here is part of the build output:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_BASENAME
    PYTHON_INCLUDE_DIR
    PYTHON_LIBRARY
```
Note that these are precisely the lines that hardcode `python3.7` in the PKGBUILD.

**Comment by petronny** [comment]
Glad to here that the hardcoded part is not relevant.
Anyway, this package has been rebuilt and will be rebuilt automatically when python updates.

4e07c4d8494783181834c6c4c6c

**Comment by jwhendy** [comment]
Thanks for the quick response, @petronny !
