### ISSUE TITLE
[Request] please package heasoft

### ISSUE THREAD

**Issue by holymonson** [arch4edu/arch4edu#66]
[HEASoft](https://heasarc.gsfc.nasa.gov/docs/software/heasoft/) is a data analysis toolset for High Energy Physics and Astronomy, developed by NASA. 
Ready in [AUR](https://aur.archlinux.org/packages/heasoft).

**Comment by holymonson** [comment]
Thanks @petronny , should this be considered done and closed? But the package seems not in the repo?

**Comment by holymonson** [comment]
Hi @petronny, heasoft on AUR has been updated with the parallel build issue solved. Would you please build again?

**Comment by petronny** [comment]
05f9c4f
