### ISSUE TITLE
[Request] `qgroundcontrol`

### ISSUE THREAD

**Issue by acxz** [arch4edu/arch4edu#67]
https://aur.archlinux.org/packages/qgroundcontrol

**Comment by petronny** [comment]
```
arch4edu/qgroundcontrol 4.0.4-1 (52.1 MiB 178.8 MiB)
    Micro air vehicle ground control station.
```
Hi, we are providing this package for a long time in both x86_64 and aarch64.

**Comment by acxz** [comment]
I guess it slipped past me. Thank you so much for hosting these packages!
