### ISSUE TITLE
[Proposal] Try packaging via github actions

### ISSUE THREAD

**Issue by holymonson** [arch4edu/arch4edu#68]
I have built an proto (https://github.com/holymonson/repo/actions) to automate packaging via github actions, and introduced it to archlinuxcn on https://github.com/archlinuxcn/repo/issues/1575 .

If arch4edu takes an interest in github actions, I'd like to make a PR to show what could benefit us. Or close this issue, if you rather not.

**Comment by petronny** [comment]
初衷是好的，但是有几点问题，在这些问题解决前还是不能应用的。

1. 从[这里](https://github.com/holymonson/repo/actions/runs/81924180/workflow)来看的话，没有使用devtools打包。
我只认同使用devtools的打包，因为它是Archlinux的指定的打包工具。
其他打包工具可能可行，然而从对用户的角度来说可靠度不够。
如果你认为比如docker的工具有足够的优越性，请去archlinux的邮件列表讨论。
如果TU们认同docker进入`[extra]`甚至`[core]`，那么可以考虑。
1. 基于github actions的打包，我有以下几点疑问。
我先我声明我对github actions还不是很了解，以下内容完全基于猜测。
    1. 首先，我猜测是github actions是通过commit或者issue的创建或其他变化来触发打包流程。
对于`*-git`的包，那么使用对应仓库的commit来触发action是合理的。
但是对于非`*-git`的包，是否需要在其他地方运行类似`nvchecker`的工具来检查更新并生成commit或者issue来触发action?
    1. 在上一点成立的前提下，如果某次打包失败了，那么这个commit或者issue就白创建了，下一次`nvchecker`还是会生成新的commit或者issue。如果某个包连续失败，则会产生大量的spam commit和issue。
    1. 我不认为github actions有缓存某些文件的功能。如果要打包`gcc-git`的话，难道每次都要clone一个完整的gcc repo么？这里会产生大量的流量浪费
    1. 仅从[这里](https://github.com/holymonson/repo/actions/runs/81924180/workflow)来看的话，没有涉及处理包含非官方源依赖关系的情况。比如要打包一个包a，其依赖于官方源中的包b和arch4edu中的包c和不适合分发的包d，则pacman可以处理包b的依赖，通过修改pacman.conf可以解决一部分包c的依赖（因为涉及同步延时），包d则只能把d-pkgver.pkg.tar.zst上传至github action的流程。然而此时若包d-pkgver.pkg.tar.zst的体积很大，则这里也会产生大量的流量浪费。
    1. 对于官方源中的依赖而言，也涉及大量的流量浪费，比如cuda，如果每次都重新下载的话，感觉对mirror也会造成不小的负载。
1. 请尊重其他组织的工作，用中性的语句描述客观事实。

**Comment by holymonson** [comment]
1. archlinux 指定的打包工具是（pacman包里的）makepkg；devtools只是一些方便打包和发布（创建干净环境、查找依赖关系和将包在repo间移动）的脚本集，真正执行打包的还是底层调用的makepkg。（devtools代码很清楚）
    1. devtools创建chroot环境，是为了限制不安全的PKBUILD。如果在打包机上，我也不推荐用docker环境，因为太重了，杀鸡焉用牛刀；但现在github actions直接就提供docker环境，牛刀就在手边，不用白不用。
    2. 实际上，是可以在docker环境里用devtools创建chroot环境再调用makepkg的，但没有啥必要啊，就像N95里面套个外科口罩。docker本身就是个只有base的官方镜像，装个base-devel和加个普通用户就可以直接打包了，干净得很。
    3. 说起可靠度，你们在打包机上的操作，用户不可知，只能无条件信任；交由github自动化处理，一切脚本、命令和日志都是对所有人公开可审计，透明度我觉得是有所提高的。
2. github actions是可以通过commit、issue或者comment的创建触发，甚至是一个外部的`curl`命令。而“检查需不需要打包”和“打包”是两个独立的事件。所以：
    1. 可以只检查、不打包，例如放个 _DONTBUILD_ 文件就可以实现。
    2. 即使不需要打包（PKDBUILD没有更新），也可以人工用`curl`命令触发打包，不需要commit、issue或者comment的创建（虽然也可以）。
3. 我以为，arch4edu只是提供一个预编译的repo，而不是要创建自己的AUR。那么：
    1. 不需要运行类似nvchecker的工具来检查更新，一个包out-of-date了是AUR的事情，我们只要盯着AUR就可以了；而不要创建和上游AUR不一致的PKDBUILD（例如之前改heasoft的SHA256我就有点敏感）。
    2. AUR上的PKDBUILD应该是都成功的，如果有失败该去AUR找maintainer修，如果长期失败很烦，那就先放个 _DONTBUILD_ 文件暂停吧。
4. 我觉得，_*-git_ 包是不适合放进预编译的repo的。因为 _*-git_ 更新过分频繁，耗费大量的计算资源和流量，而且不稳定，而绝大多数人不需要。其更新频率又限制于repo的打包频率，如果有人确实需要用最新的，那该自己在本机上makepkg才能保证最新。
    1. github actions 确实是可以有缓存的。https://github.com/actions/cache
    2. git 是支持 shallow clone的，不需要传送过往的历史数据，但makepkg还不支持，如果有人去提个patch可能就能实现吧。（虽然我觉得意义不大）
    3. 相对于编译的计算资源，clone一个git repo的流量成本其实不算什么。而且那是github的流量成本，甚至很多 git repo 就是github自己的内部流量。
5. 把一个不适合分发的包d放进打包环境，我觉得是远比 怎么创建这个打包环境 要不可靠的事情啊。只要有人工介入，都不如纯机器脚本可信。
    1. 如果是需要同时更新的包，官方做法是设立 stage repo，再一起转移。
    2. github actions构建的包是可以[上传成artifact](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts)，能暂存90天，能在job之间共享，能点击下载；但跨workflow似乎是不可以的，所以需要考虑一个workflow里开多个job打包一系列的包。（设置会比较复杂但貌似也不是绝不可行）
    3. 基础包多在官方仓库里，arch4edu里的该多是终端包，这样的包多么？而且如果一个包因为依赖升级需要重新构建，那么AUR里该有pkgrel更新的吧。
    4. 流量浪费相对于计算资源我真觉得可以接受。
6. 我没有提议要应用马上替换掉lilac，只是如果两套系统同时开，github actions上打好的包就丢掉，除了浪费一下github的资源和会有告警通知（还是可以关掉的），你们似乎也没有什么太大损失吧？
7. Sorry，会修改用词。

**Comment by petronny** [comment]
1. 
> 实际上，是可以在docker环境里用devtools创建chroot环境再调用makepkg的

如果可能的话我坚持这么做，因为我不想在维护一个在docker里自动更新、安装依赖等等步骤的工具，有现成轮子就用现成轮子，不要额外增加维护负担。

2. 
> 也可以人工用curl命令触发打包

ok，如何触发的问题可以解决

3.

> AUR上的PKDBUILD应该是都成功的

其实超多都有问题。对每个包都需要有专门的文件对其做修正。这也是lilac.py的主要用途之一。
不过我相信github actions下也应该可以实现。

4.

> *-git 包是不适合放进预编译的repo的

是这样，所以加-git包时必须要有一定的原因。然而还是会有一些这样的包的，比如没有非-git版的，还有一些需要最新feature的。所以相关问题必须要考虑。

5.

> 这样的包多么？

有非官方源的依赖包c的情形非常多。这个可能是需要重点解决的问题。

不适合分发的包在打包cuda相关的东西时经常会遇到，原来有cudnn，现在有nvidia-sdk这种。
然而基于它们打包的opencv-cuda是可以分发的。总体来说是偶尔需要处理的问题。

6. 

> 两套系统同时开

还是等依赖关系进一步解决了吧。不光有装依赖的问题，还有被依赖的包打包失败时，后面的打包流程要报错的问题。

初步建议是还是通过lilac来决定哪些包要打以及打包顺序。
通过一个叫github-actions-build的脚本替代extra-x86_64-build执行打包。注意这个需要是阻塞式的，即这个脚本启动时，对应的github-action打包流程会启动，并在github-action打包流程中止之后再中止。这个脚本内部通过curl来触发github-action。最后返回打包是否成功或失败。

你可以从这个github-actions-build入手。做好了（cache、依赖等等都解决了）可以引入并替代几个现有的`build_prefix`试试。

另外针对于github-actions效率低的问题，有一个思路是并行打包，github-actions的并行是怎样的？是单个repo内就可以并行，
还是同账号多repo可以并行，
还是多账号可以并行，
还是多账号也得排队？
如果多账号也得排队的话，那github-actions-build也只能小范围应用一下。

**Comment by holymonson** [comment]
抱歉，近来比较忙忘这事了，不过既然兴趣不大那就算了吧，我个人也没啥影响，thanks。
