### ISSUE TITLE
[Request] Various packages

### ISSUE THREAD

**Issue by acxz** [arch4edu/arch4edu#72]
Many packages that I have been maintaining which take a decent time to build.

- [x] [libdart](https://aur.archlinux.org/packages/libdart/)
    - [x] fcl
- [x] [ompl](https://aur.archlinux.org/packages/ompl/)
- [ ] [ompl-app](https://aur.archlinux.org/packages/omplapp/)
- [x] [openvsp](https://aur.archlinux.org/packages/openvsp/)
- [x] [python-pygmo](https://aur.archlinux.org/packages/python-pygmo/)
   - [x] [pagmo](https://aur.archlinux.org/packages/pagmo/)
- [ ] [python-ray](https://aur.archlinux.org/packages/python-ray/)
  - [ ] py-spy
  - [ ] python-aioredis
  - [ ] python-colorful
  - [ ] python-google
  - [ ] python-gpustat
  - [ ] python-opencensus
- [x] xflr5
- [ ] [gazebo](https://aur.archlinux.org/packages/gazebo)

**Comment by adrianinsaval** [comment]
+1 yo openvsp
Maybe xflr5 too?

**Comment by acxz** [comment]
lol yeah xflr5 also takes a while to build

**Comment by acxz** [comment]
Closing this issue as some packages are not of interest anymore.
