### ISSUE TITLE
Removal of `hcc` breaks rocm packages

### ISSUE THREAD

**Issue by chengyuhui** [arch4edu/arch4edu#79]
I was about to install `rocm-dkms` on my system when I noticed that it has unsatisfied deps, such as `hcc` and `hip-hcc`, which were removed in 7a38d11.

I understand the decision since these packages are deprecated, but removing them now makes some rocm packages completely useless, is there any way around it?

**Comment by petronny** [comment]
The rocm project is upgrading to 3.5.0 but it still WIP.

See https://github.com/rocm-arch/rocm-arch/issues/168

> is there any way around it?

I think the best way is to wait for the `rocm-dkms` part is solve in https://github.com/rocm-arch/rocm-arch/issues/168 .

**Comment by chengyuhui** [comment]
I understand that there is a WIP. However, is it a good idea to leave packages in a broken state here?

**Comment by tpkessler** [comment]
Hey @chengyuhui! Could please open an issue on https://github.com/rocm-arch/rocm-arch for this? A possible workaround is to not install the meta package `rocm-dkms` but to pick the packages from `rocm-dev` you need at the moment.

**Comment by chengyuhui** [comment]
Yeah, that's probably needed, since their AUR packages are also broken because of the removal.

**Comment by petronny** [comment]
`rocm-dkms` has been updated to 3.5.0
