### ISSUE TITLE
med和parmetis的hdf5和openmpi依赖由于archlinux升级被破坏...

### ISSUE THREAD

**Issue by heavysink** [arch4edu/arch4edu#8]
最新archlinux更新把libhdf5.so.100升级成了libhdf5.so.101,openmpi里面libmpi.so.12升级成了libmpi.so.20，导致这两个包对libhdf5.so.100和libmpi.so.12的依赖被破坏。bot端能否重新编译一下？

以后依赖于openmpi的包要格外留意，因为升级比较频繁，而很多软件包是直接链到libmpi.so.XX而不是libmpi.so上的。

**Comment by petronny** [comment]
这个情况现在除了及时rebuild这些包好像就没什么好办法了。。。

**Comment by heavysink** [comment]
不知道你的buildbot是否有依赖升级后自动触发重编译的功能？不过这对buildbot是个不小的负担。

**Comment by petronny** [comment]
lilac现在还没有这个功能。。
