### ISSUE TITLE
unresolvable dependencies during installation of rocm-dkms

### ISSUE THREAD

**Issue by chiboreache** [arch4edu/arch4edu#82]
<img width="892" alt="Screenshot_20200617_095716" src="https://user-images.githubusercontent.com/16459251/84866402-56fed600-b082-11ea-979f-e6af5cc915b9.png">

`Server = https://mirrors.tuna.tsinghua.edu.cn/arch4edu/$arch`

**Comment by petronny** [comment]
Duplicated to #79
