### ISSUE TITLE
[package request] python-pytorch-rocm

### ISSUE THREAD

**Issue by chiboreache** [arch4edu/arch4edu#84]
would be nice

ps: i know about aur version, but it won't compile  -_-

**Comment by acxz** [comment]
@chiboreache if you could post the issues you have for the aur package of `python-pytorch-(opt-)rocm` over at https://github.com/rocm-arch/python-pytorch-rocm that would be much appreciated.

**Comment by petronny** [comment]
Please let me know when it's fixed.

**Comment by acxz** [comment]
@petronny we got the package building, if you could add this package to arch4edu that would be much appreciated!

**Comment by petronny** [comment]
Great. BTW, is tensorflow-rocm working?

**Comment by acxz** [comment]
Not yet, we are still working on it. I'll open up another package request for it once we do get it building.

**Comment by petronny** [comment]
194c1b2ef169d673a9cf042299acd6c2ae361889

The build server can't build `python-pytorch-opt-rocm` because it doesn't have a haswell CPU.

**Comment by acxz** [comment]
ah that flag was prob specified for the Arch Linux devs build server, I should be able to take it out and it should work I think. I'll ping once I make the change.

Once again man thanks soo much for this. You really a hero man.

**Comment by petronny** [comment]
You are welcome.

I've already make the changes with lilac (df367dc6658ec233722dbcb9ca4ed49e45acebc0).
No need to fix the PKGBUILD on AUR.

**Comment by chiboreache** [comment]
**VICTORY!**

![Screenshot_20200809_000545](https://user-images.githubusercontent.com/16459251/89719733-22e5c880-d9d4-11ea-88e6-46ea8ae8b7a9.png)
