### ISSUE TITLE
Any issues adding this repo to Manjaro?

### ISSUE THREAD

**Issue by bernharl** [arch4edu/arch4edu#86]
If I were to add this repo to Manjaro, would that create issues with partial upgrades as the binaries here are built with respect to the Arch repos, while the Manjaro repos are often a week or so behind the official Arch repos?

I'm hesitant to try it out for myself in case of breakage.

**Comment by petronny** [comment]
I never used Manjaro before.
But I think those issues will occur if the Manjaro repos are often a week or so behind the official Arch repos.

We may offer an `[arch4edu-manjaro]` repository in the future.
But there are lots of issues to do to archieve that.

For now, you may want to use this repo inside an archlinux docker container.
Or just use the [arch4edu docker image](https://cloud.docker.com/u/arch4edu/repository/docker/arch4edu/base), `arch4edu/base:latest`.

**Comment by bernharl** [comment]
Thanks! 

I'll try the Docker image or just replace Manjaro by regular Arch then.

**Comment by acxz** [comment]
@bernharl another distribution to look at is [Endeavouros](https://endeavouros.com/). Unlike Manjaro, it is Arch repo compatible since it uses the same package repos as Arch. It has a gui install if thats the reason why you choose Manjaro over Arch.

**Comment by bernharl** [comment]
@acxz Thank you for the tip. I'll probably be switching to Arch though as I have no problem with the installation, it's just that I can't be bothered reformatting my computer at the moment. Thank you for your amazing efforts getting ROCM to work on Arch by the way!

**Comment by SamLukeYes** [comment]
The most up-to-date branch of Manjaro is call "unstable branch". However, if you're using a 3rd-party repo that is built for Arch, unstable branch is even stabler than stable branch.

**Comment by petronny** [comment]
Hi, there is an issue to discuss about the manjaro support at #169.
