### ISSUE TITLE
Package Request: openboard

### ISSUE THREAD

**Issue by iyanmv** [arch4edu/arch4edu#89]
A nice application to substitute whiteboards. I started to use it because of coronavirus restrictions and I find it very useful while doings videoconferences. Way more powerful than integrated solutions in conference apps such as Zoom, BigBlueButton, Cisco Webex, etc.

https://openboard.ch

https://aur.archlinux.org/packages/openboard/

**Comment by petronny** [comment]
494a0a7e48fb70f3a04c244d8456964648b2e7b5
