### ISSUE TITLE
Package request: aomp-amdgpu

### ISSUE THREAD

**Issue by tpkessler** [arch4edu/arch4edu#90]
Hey @petronny!

 I've got a new package from the ROCm stack for which it would be great to have a binary package: [`aomp-amdgpu`](https://aur.archlinux.org/packages/aomp-amdgpu). It's a OpenMP 5.0 compiler for offloading computation on AMD GPUs. Among other libraries it includes `LLVM/clang` which takes awfully long to compile. I've already successfully built the package in a clean chroot.

**Comment by petronny** [comment]
903eed2

**Comment by petronny** [comment]
6e470b8bac8419e30b3c378bfe001152a134f077
