### ISSUE TITLE
python-numpy-mkl should depend on intel-common-libs

### ISSUE THREAD

**Issue by SamLukeYes** [arch4edu/arch4edu#91]
numpy+mkl needs libimf.so, which is included in intel-common-libs. If it doesn't exist, Python will raise ImportError when importing numpy. Please add intel-common-libs to the dependencies of python-numpy-mkl.

**Comment by petronny** [comment]
I will discuss with the maintainer of python-numpy-mkl about if we should build it with icc first.

**Comment by petronny** [comment]
python-numpy-mkl now depends on the new intel-oneapi packages.
This issue seems to be fixed.
