### ISSUE TITLE
[Request] openfoam-esi

### ISSUE THREAD

**Issue by MakisH** [arch4edu/arch4edu#94]
The [openfoam-esi](https://aur.archlinux.org/packages/openfoam-esi/) package provides the ESI/OpenCFD variant of OpenFOAM (openfoam.com).

There are currently two projects named "OpenFOAM": One from The OpenFOAM Foundation (openfoam.org) and one from OpenCFD / ESI (openfoam.com). The two projects are being developed in parallel, share some parts, but also differ in other parts. They also both take ages to build.

[You already provide openfoam](https://github.com/arch4edu/arch4edu/tree/master/openfoam), it would be nice to also have prebuilt pinaries for openfoam-esi here.

Both projects are very useful for students and researchers working with Computational Fluid Dynamics simulations.

**Comment by petronny** [comment]
As you have [commented](https://aur.archlinux.org/packages/openfoam-esi/#comment-759093),
there are some issues when building this package.

Please let me know when they are solved. Especially the second one.

**Comment by MakisH** [comment]
@petronny everything has now been fixed and the package is in a very good state now. Thank you for picking this up. :hugs:

**Comment by petronny** [comment]
6014f07922e296eed4b626ae22de10ea12de62e7
