### ISSUE TITLE
add openfoam-selector for managing openfoam flavours and versions

### ISSUE THREAD

**Issue by olesenm** [arch4edu/arch4edu#97]
Looking at the two openfoam recipes, it could be useful to add in the openfoam-selector. This is much like the mpi-selector that allows registration and selection of various openfoam installations, either system-wide or per-user.

Typically would use trigger to register them. For example, like these debian triggers,
- [Package postinst](https://github.com/arch4edu/arch4edu/files/5069857/Package.postinst.txt)
- [Package postrm](https://github.com/arch4edu/arch4edu/files/5069859/Package.postrm.txt)

The PKGBUILD would be rather straightforward:

- source:  https://sourceforge.net/projects/openfoam/files/utils/openfoam-selector-1.0.6.tgz
- repo:  https://develop.openfoam.com/Community/feature-scripts/-/tree/develop/openfoam-selector
```
./configure --with-shell-startup-dir=/etc/profile.d
make
make DESTDIR=%{buildroot} install
```
Or possibly with
```
./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --with-sysconf-dir=/etc/openfoam \
    --with-shell-startup-dir=/etc/profile.d
```

**Comment by olesenm** [comment]
@MakisH

**Comment by petronny** [comment]
Please let me know when there is an `openfoam-selector` package on AUR.

**Comment by olesenm** [comment]
@makish - would you be willing to put one together for arch? I don't yet have arch anywhere, but the selector is a really simple package (only depend is perl), but makes life ***so much*** easier for users. Can select various versions/flavours. For the packaging of OpenFOAM, the triggers are also easy to use.

Danke im Voraus
/mark

**Comment by MakisH** [comment]
@olesenm yes, I can look at it in a few days, it would be a nice addition. I currently only have a Manjaro installation in a poor VM, though, it takes some time to build.

**Comment by MakisH** [comment]
@olesenm @petronny  I published the [openfoam-selector package](https://aur.archlinux.org/packages/openfoam-selector/).

**Comment by petronny** [comment]
006358803e285d56680191b5bb3c35232bb3bcfc
